/** @type {import('next').NextConfig} */
const nextConfig = {
  poweredByHeader: false,
  compress: true,
  compiler: {
    removeConsole: process.env.NODE_ENV === 'production' ? { exclude: ['error', 'warn'] } : false,
  },
  images: {
    formats: ['image/avif', 'image/webp'],
    minimumCacheTTL: 86400,
    remotePatterns: [
      { protocol: 'https', hostname: 'login.louislawgroup.com' },
    ],
  },
  async redirects() {
    return [
      // ── CRO 2026-06-20: recover 404 on canonical SSDI slug → live SSDI landing page ──
      { source: '/social-security-disability', destination: '/ssdi-lawyers', permanent: true },
      // ── P0 redirects: 404 → live canonical pages ──
      { source: '/property-damage-insurance-claim', destination: '/property-damage-claims', permanent: true },
      { source: '/tower-hill-insurance-denied-claim-florida', destination: '/tower-hill-insurance-denied-claim-florida-2026', permanent: true },
      { source: '/water-damage-insurance-claim-florida-homeowner', destination: '/property-damage-claims', permanent: true },
      // ── SEO P0b 2026-06-18: SSDI twin consolidation (base -> -N earner) ──
      { source: '/anxiety-disability-benefits-2026', destination: '/anxiety-disability-benefits-2026-11', permanent: true },
      { source: '/average-ssdi-payment-arizona-2026', destination: '/average-ssdi-payment-arizona-2026-3', permanent: true },
      { source: '/average-ssdi-payment-hawaii-2026', destination: '/average-ssdi-payment-hawaii-2026-3', permanent: true },
      { source: '/average-ssdi-payment-illinois-2026', destination: '/average-ssdi-payment-illinois-2026-5', permanent: true },
      { source: '/average-ssdi-payment-kentucky-2026', destination: '/average-ssdi-payment-kentucky-2026-7', permanent: true },
      { source: '/average-ssdi-payment-maine-2026', destination: '/average-ssdi-payment-maine-2026-5', permanent: true },
      { source: '/average-ssdi-payment-maryland-2026', destination: '/average-ssdi-payment-maryland-2026-5', permanent: true },
      { source: '/average-ssdi-payment-michigan-2026', destination: '/average-ssdi-payment-michigan-2026-13', permanent: true },
      { source: '/average-ssdi-payment-missouri-2026', destination: '/average-ssdi-payment-missouri-2026-3', permanent: true },
      { source: '/average-ssdi-payment-ohio-2026', destination: '/average-ssdi-payment-ohio-2026-7', permanent: true },
      { source: '/average-ssdi-payment-tennessee-2026', destination: '/average-ssdi-payment-tennessee-2026-17', permanent: true },
      { source: '/average-ssdi-payment-washington-2026', destination: '/average-ssdi-payment-washington-2026-9', permanent: true },
      { source: '/average-ssdi-payment-wisconsin-2026', destination: '/average-ssdi-payment-wisconsin-2026-4', permanent: true },
      { source: '/back-pain-disability-benefits-2026', destination: '/back-pain-disability-benefits-2026-2', permanent: true },
      { source: '/bakersfield-ssdi-representation-2026', destination: '/bakersfield-ssdi-representation-2026-3', permanent: true },
      { source: '/best-ssdi-attorney-albany-2026', destination: '/best-ssdi-attorney-albany-2026-2', permanent: true },
      { source: '/best-ssdi-attorney-las-vegas-2026', destination: '/best-ssdi-attorney-las-vegas-2026-2', permanent: true },
      { source: '/best-ssdi-attorney-tulsa-2026', destination: '/best-ssdi-attorney-tulsa-2026-2', permanent: true },
      { source: '/bipolar-disorder-disability-benefits-2026', destination: '/bipolar-disorder-disability-benefits-2026-5', permanent: true },
      { source: '/can-i-work-while-on-ssdi-2026', destination: '/can-i-work-while-on-ssdi-2026-86', permanent: true },
      { source: '/cancer-disability-benefits-2026', destination: '/cancer-disability-benefits-2026-16', permanent: true },
      { source: '/colorado-ssdi-application-process-2026', destination: '/colorado-ssdi-application-process-2026-6', permanent: true },
      { source: '/copd-disability-benefits-2026', destination: '/copd-disability-benefits-2026-40', permanent: true },
      { source: '/crohns-disease-disability-benefits-2026', destination: '/crohns-disease-disability-benefits-2026-31', permanent: true },
      { source: '/depression-disability-benefits-2026', destination: '/depression-disability-benefits-2026-39', permanent: true },
      { source: '/disability-appeal-lawyer-denver-2026', destination: '/disability-appeal-lawyer-denver-2026-2', permanent: true },
      { source: '/disability-appeal-lawyer-detroit-2026', destination: '/disability-appeal-lawyer-detroit-2026-3', permanent: true },
      { source: '/disability-appeal-lawyer-el-paso-2026', destination: '/disability-appeal-lawyer-el-paso-2026-7', permanent: true },
      { source: '/disability-appeal-lawyer-orlando-2026', destination: '/disability-appeal-lawyer-orlando-2026-4', permanent: true },
      { source: '/disability-appeal-lawyer-portland-2026', destination: '/disability-appeal-lawyer-portland-2026-2', permanent: true },
      { source: '/disability-appeal-lawyer-seattle-2026', destination: '/disability-appeal-lawyer-seattle-2026-3', permanent: true },
      { source: '/disability-attorney-milwaukee-2026', destination: '/disability-attorney-milwaukee-2026-2', permanent: true },
      { source: '/disability-attorney-nashville-2026', destination: '/disability-attorney-nashville-2026-3', permanent: true },
      { source: '/disability-attorney-reno-2026', destination: '/disability-attorney-reno-2026-2', permanent: true },
      { source: '/disability-attorney-sacramento-2026', destination: '/disability-attorney-sacramento-2026-3', permanent: true },
      { source: '/disability-claim-denied-arkansas-2026', destination: '/disability-claim-denied-arkansas-2026-3', permanent: true },
      { source: '/disability-claim-denied-california-2026', destination: '/disability-claim-denied-california-2026-4', permanent: true },
      { source: '/disability-claim-denied-idaho-2026', destination: '/disability-claim-denied-idaho-2026-2', permanent: true },
      { source: '/disability-claim-denied-minnesota-2026', destination: '/disability-claim-denied-minnesota-2026-4', permanent: true },
      { source: '/disability-claim-denied-new-york-2026', destination: '/disability-claim-denied-new-york-2026-5', permanent: true },
      { source: '/disability-claim-denied-south-carolina-2026', destination: '/disability-claim-denied-south-carolina-2026-3', permanent: true },
      { source: '/disability-claim-denied-texas-2026', destination: '/disability-claim-denied-texas-2026-8', permanent: true },
      { source: '/disability-claim-denied-washington-2026', destination: '/disability-claim-denied-washington-2026-20', permanent: true },
      { source: '/disability-claim-denied-wyoming-2026', destination: '/disability-claim-denied-wyoming-2026-22', permanent: true },
      { source: '/disability-hearing-arkansas-2026', destination: '/disability-hearing-arkansas-2026-7', permanent: true },
      { source: '/disability-hearing-california-2026', destination: '/disability-hearing-california-2026-3', permanent: true },
      { source: '/disability-hearing-georgia-2026', destination: '/disability-hearing-georgia-2026-4', permanent: true },
      { source: '/disability-hearing-maryland-2026', destination: '/disability-hearing-maryland-2026-7', permanent: true },
      { source: '/disability-hearing-missouri-2026', destination: '/disability-hearing-missouri-2026-7', permanent: true },
      { source: '/disability-hearing-new-jersey-2026', destination: '/disability-hearing-new-jersey-2026-5', permanent: true },
      { source: '/disability-hearing-oklahoma-2026', destination: '/disability-hearing-oklahoma-2026-5', permanent: true },
      { source: '/disability-hearing-oregon-2026', destination: '/disability-hearing-oregon-2026-12', permanent: true },
      { source: '/disability-hearing-texas-2026', destination: '/disability-hearing-texas-2026-2', permanent: true },
      { source: '/disability-hearing-washington-2026', destination: '/disability-hearing-washington-2026-10', permanent: true },
      { source: '/disability-lawyer-near-grand-rapids-2026', destination: '/disability-lawyer-near-grand-rapids-2026-3', permanent: true },
      { source: '/does-back-pain-qualify-for-ssdi-2026', destination: '/does-back-pain-qualify-for-ssdi-2026-4', permanent: true },
      { source: '/does-bipolar-disorder-qualify-for-ssdi-2026', destination: '/does-bipolar-disorder-qualify-for-ssdi-2026-22', permanent: true },
      { source: '/does-cancer-qualify-for-ssdi-2026', destination: '/does-cancer-qualify-for-ssdi-2026-9', permanent: true },
      { source: '/does-chronic-fatigue-syndrome-qualify-for-ssdi-2026', destination: '/does-chronic-fatigue-syndrome-qualify-for-ssdi-2026-19', permanent: true },
      { source: '/does-crohns-disease-qualify-for-ssdi-2026', destination: '/does-crohns-disease-qualify-for-ssdi-2026-3', permanent: true },
      { source: '/does-diabetes-complications-qualify-for-ssdi-2026', destination: '/does-diabetes-complications-qualify-for-ssdi-2026-21', permanent: true },
      { source: '/does-epilepsy-qualify-for-ssdi-2026', destination: '/does-epilepsy-qualify-for-ssdi-2026-5', permanent: true },
      { source: '/does-neuropathy-qualify-for-ssdi-2026', destination: '/does-neuropathy-qualify-for-ssdi-2026-7', permanent: true },
      { source: '/el-paso-disability-lawyer-2026', destination: '/el-paso-disability-lawyer-2026-2', permanent: true },
      { source: '/epilepsy-disability-benefits-2026', destination: '/epilepsy-disability-benefits-2026-9', permanent: true },
      { source: '/fort-lauderdale-disability-lawyer-2026', destination: '/fort-lauderdale-disability-lawyer-2026-3', permanent: true },
      { source: '/getting-disability-for-anxiety-2026', destination: '/getting-disability-for-anxiety-2026-13', permanent: true },
      { source: '/getting-disability-for-back-pain-2026', destination: '/getting-disability-for-back-pain-2026-13', permanent: true },
      { source: '/getting-disability-for-cancer-2026', destination: '/getting-disability-for-cancer-2026-14', permanent: true },
      { source: '/getting-disability-for-chronic-fatigue-syndrome-2026', destination: '/getting-disability-for-chronic-fatigue-syndrome-2026-7', permanent: true },
      { source: '/getting-disability-for-copd-2026', destination: '/getting-disability-for-copd-2026-18', permanent: true },
      { source: '/getting-disability-for-depression-2026', destination: '/getting-disability-for-depression-2026-6', permanent: true },
      { source: '/getting-disability-for-epilepsy-2026', destination: '/getting-disability-for-epilepsy-2026-5', permanent: true },
      { source: '/getting-disability-for-fibromyalgia-2026', destination: '/getting-disability-for-fibromyalgia-2026-18', permanent: true },
      { source: '/getting-disability-for-heart-failure-2026', destination: '/getting-disability-for-heart-failure-2026-34', permanent: true },
      { source: '/getting-disability-for-lupus-2026', destination: '/getting-disability-for-lupus-2026-8', permanent: true },
      { source: '/getting-disability-for-ptsd-2026', destination: '/getting-disability-for-ptsd-2026-19', permanent: true },
      { source: '/getting-disability-for-rheumatoid-arthritis-2026', destination: '/getting-disability-for-rheumatoid-arthritis-2026-23', permanent: true },
      { source: '/heart-failure-disability-benefits-2026', destination: '/heart-failure-disability-benefits-2026-6', permanent: true },
      { source: '/herniated-disc-disability-benefits-2026', destination: '/herniated-disc-disability-benefits-2026-33', permanent: true },
      { source: '/how-long-does-ssdi-take-in-alabama-2026', destination: '/how-long-does-ssdi-take-in-alabama-2026-12', permanent: true },
      { source: '/how-long-does-ssdi-take-in-florida-2026', destination: '/how-long-does-ssdi-take-in-florida-2026-5', permanent: true },
      { source: '/how-long-does-ssdi-take-in-illinois-2026', destination: '/how-long-does-ssdi-take-in-illinois-2026-9', permanent: true },
      { source: '/how-long-does-ssdi-take-in-kentucky-2026', destination: '/how-long-does-ssdi-take-in-kentucky-2026-2', permanent: true },
      { source: '/how-long-does-ssdi-take-in-michigan-2026', destination: '/how-long-does-ssdi-take-in-michigan-2026-4', permanent: true },
      { source: '/how-long-does-ssdi-take-in-missouri-2026', destination: '/how-long-does-ssdi-take-in-missouri-2026-9', permanent: true },
      { source: '/how-long-does-ssdi-take-in-new-hampshire-2026', destination: '/how-long-does-ssdi-take-in-new-hampshire-2026-10', permanent: true },
      { source: '/how-long-does-ssdi-take-in-new-jersey-2026', destination: '/how-long-does-ssdi-take-in-new-jersey-2026-9', permanent: true },
      { source: '/how-long-does-ssdi-take-in-north-carolina-2026', destination: '/how-long-does-ssdi-take-in-north-carolina-2026-3', permanent: true },
      { source: '/how-long-does-ssdi-take-in-west-virginia-2026', destination: '/how-long-does-ssdi-take-in-west-virginia-2026-3', permanent: true },
      { source: '/how-many-work-credits-for-ssdi-2026', destination: '/how-many-work-credits-for-ssdi-2026-276', permanent: true },
      { source: '/how-much-does-ssdi-pay-in-alabama-2026', destination: '/how-much-does-ssdi-pay-in-alabama-2026-13', permanent: true },
      { source: '/how-much-does-ssdi-pay-in-georgia-2026', destination: '/how-much-does-ssdi-pay-in-georgia-2026-17', permanent: true },
      { source: '/how-much-does-ssdi-pay-in-iowa-2026', destination: '/how-much-does-ssdi-pay-in-iowa-2026-5', permanent: true },
      { source: '/how-much-does-ssdi-pay-in-minnesota-2026', destination: '/how-much-does-ssdi-pay-in-minnesota-2026-5', permanent: true },
      { source: '/how-much-does-ssdi-pay-in-mississippi-2026', destination: '/how-much-does-ssdi-pay-in-mississippi-2026-7', permanent: true },
      { source: '/how-much-does-ssdi-pay-in-nebraska-2026', destination: '/how-much-does-ssdi-pay-in-nebraska-2026-10', permanent: true },
      { source: '/how-much-does-ssdi-pay-in-new-jersey-2026', destination: '/how-much-does-ssdi-pay-in-new-jersey-2026-6', permanent: true },
      { source: '/how-much-does-ssdi-pay-in-pennsylvania-2026', destination: '/how-much-does-ssdi-pay-in-pennsylvania-2026-5', permanent: true },
      { source: '/how-much-does-ssdi-pay-in-rhode-island-2026', destination: '/how-much-does-ssdi-pay-in-rhode-island-2026-14', permanent: true },
      { source: '/how-to-appeal-ssdi-denial-alabama-2026', destination: '/how-to-appeal-ssdi-denial-alabama-2026-6', permanent: true },
      { source: '/how-to-appeal-ssdi-denial-minnesota-2026', destination: '/how-to-appeal-ssdi-denial-minnesota-2026-8', permanent: true },
      { source: '/how-to-appeal-ssdi-denial-oregon-2026', destination: '/how-to-appeal-ssdi-denial-oregon-2026-5', permanent: true },
      { source: '/how-to-appeal-ssdi-denial-virginia-2026', destination: '/how-to-appeal-ssdi-denial-virginia-2026-2', permanent: true },
      { source: '/how-to-apply-for-ssdi-in-arizona-2026', destination: '/how-to-apply-for-ssdi-in-arizona-2026-3', permanent: true },
      { source: '/how-to-apply-for-ssdi-in-colorado-2026', destination: '/how-to-apply-for-ssdi-in-colorado-2026-8', permanent: true },
      { source: '/how-to-apply-for-ssdi-in-connecticut-2026', destination: '/how-to-apply-for-ssdi-in-connecticut-2026-2', permanent: true },
      { source: '/how-to-apply-for-ssdi-in-georgia-2026', destination: '/how-to-apply-for-ssdi-in-georgia-2026-2', permanent: true },
      { source: '/how-to-apply-for-ssdi-in-kansas-2026', destination: '/how-to-apply-for-ssdi-in-kansas-2026-4', permanent: true },
      { source: '/how-to-apply-for-ssdi-in-maryland-2026', destination: '/how-to-apply-for-ssdi-in-maryland-2026-3', permanent: true },
      { source: '/how-to-apply-for-ssdi-in-minnesota-2026', destination: '/how-to-apply-for-ssdi-in-minnesota-2026-8', permanent: true },
      { source: '/how-to-apply-for-ssdi-in-mississippi-2026', destination: '/how-to-apply-for-ssdi-in-mississippi-2026-5', permanent: true },
      { source: '/how-to-apply-for-ssdi-in-montana-2026', destination: '/how-to-apply-for-ssdi-in-montana-2026-2', permanent: true },
      { source: '/how-to-apply-for-ssdi-in-new-jersey-2026', destination: '/how-to-apply-for-ssdi-in-new-jersey-2026-8', permanent: true },
      { source: '/how-to-apply-for-ssdi-in-north-carolina-2026', destination: '/how-to-apply-for-ssdi-in-north-carolina-2026-6', permanent: true },
      { source: '/how-to-apply-for-ssdi-in-south-carolina-2026', destination: '/how-to-apply-for-ssdi-in-south-carolina-2026-2', permanent: true },
      { source: '/how-to-apply-for-ssdi-in-texas-2026', destination: '/how-to-apply-for-ssdi-in-texas-2026-2', permanent: true },
      { source: '/how-to-apply-for-ssdi-in-washington-2026', destination: '/how-to-apply-for-ssdi-in-washington-2026-9', permanent: true },
      { source: '/idaho-ssdi-application-process-2026', destination: '/idaho-ssdi-application-process-2026-3', permanent: true },
      { source: '/illinois-ssdi-application-process-2026', destination: '/illinois-ssdi-application-process-2026-7', permanent: true },
      { source: '/kansas-city-disability-lawyer-2026', destination: '/kansas-city-disability-lawyer-2026-3', permanent: true },
      { source: '/kentucky-ssdi-application-process-2026', destination: '/kentucky-ssdi-application-process-2026-4', permanent: true },
      { source: '/louisiana-ssdi-application-process-2026', destination: '/louisiana-ssdi-application-process-2026-7', permanent: true },
      { source: '/miami-disability-lawyer-2026', destination: '/miami-disability-lawyer-2026-2', permanent: true },
      { source: '/multiple-sclerosis-disability-benefits-2026', destination: '/multiple-sclerosis-disability-benefits-2026-3', permanent: true },
      { source: '/neuropathy-disability-benefits-2026', destination: '/neuropathy-disability-benefits-2026-18', permanent: true },
      { source: '/new-hampshire-ssdi-application-process-2026', destination: '/new-hampshire-ssdi-application-process-2026-24', permanent: true },
      { source: '/not-enough-work-credits-ssdi-california-2026', destination: '/not-enough-work-credits-ssdi-california-2026-8', permanent: true },
      { source: '/not-enough-work-credits-ssdi-florida-2026', destination: '/not-enough-work-credits-ssdi-florida-2026-9', permanent: true },
      { source: '/not-enough-work-credits-ssdi-idaho-2026', destination: '/not-enough-work-credits-ssdi-idaho-2026-7', permanent: true },
      { source: '/not-enough-work-credits-ssdi-michigan-2026', destination: '/not-enough-work-credits-ssdi-michigan-2026-5', permanent: true },
      { source: '/not-enough-work-credits-ssdi-missouri-2026', destination: '/not-enough-work-credits-ssdi-missouri-2026-8', permanent: true },
      { source: '/not-enough-work-credits-ssdi-new-jersey-2026', destination: '/not-enough-work-credits-ssdi-new-jersey-2026-7', permanent: true },
      { source: '/not-enough-work-credits-ssdi-south-carolina-2026', destination: '/not-enough-work-credits-ssdi-south-carolina-2026-3', permanent: true },
      { source: '/not-enough-work-credits-ssdi-texas-2026', destination: '/not-enough-work-credits-ssdi-texas-2026-19', permanent: true },
      { source: '/not-enough-work-credits-ssdi-washington-2026', destination: '/not-enough-work-credits-ssdi-washington-2026-3', permanent: true },
      { source: '/ohio-ssdi-application-process-2026', destination: '/ohio-ssdi-application-process-2026-5', permanent: true },
      { source: '/omaha-disability-lawyer-2026', destination: '/omaha-disability-lawyer-2026-2', permanent: true },
      { source: '/orlando-ssdi-representation-2026', destination: '/orlando-ssdi-representation-2026-6', permanent: true },
      { source: '/preparing-for-ssdi-hearing-louisiana-2026', destination: '/preparing-for-ssdi-hearing-louisiana-2026-2', permanent: true },
      { source: '/preparing-for-ssdi-hearing-new-jersey-2026', destination: '/preparing-for-ssdi-hearing-new-jersey-2026-3', permanent: true },
      { source: '/ptsd-disability-benefits-2026', destination: '/ptsd-disability-benefits-2026-5', permanent: true },
      { source: '/rheumatoid-arthritis-disability-benefits-2026', destination: '/rheumatoid-arthritis-disability-benefits-2026-8', permanent: true },
      { source: '/social-security-attorney-albuquerque-new-mexico-2026', destination: '/social-security-attorney-albuquerque-new-mexico-2026-3', permanent: true },
      { source: '/social-security-attorney-bakersfield-california-2026', destination: '/social-security-attorney-bakersfield-california-2026-7', permanent: true },
      { source: '/social-security-attorney-columbus-ohio-2026', destination: '/social-security-attorney-columbus-ohio-2026-2', permanent: true },
      { source: '/social-security-attorney-fort-lauderdale-florida-2026', destination: '/social-security-attorney-fort-lauderdale-florida-2026-2', permanent: true },
      { source: '/social-security-attorney-pittsburgh-pennsylvania-2026', destination: '/social-security-attorney-pittsburgh-pennsylvania-2026-3', permanent: true },
      { source: '/social-security-attorney-providence-rhode-island-2026', destination: '/social-security-attorney-providence-rhode-island-2026-3', permanent: true },
      { source: '/social-security-attorney-richmond-virginia-2026', destination: '/social-security-attorney-richmond-virginia-2026-2', permanent: true },
      { source: '/social-security-disability-application-california-2026', destination: '/social-security-disability-application-california-2026-2', permanent: true },
      { source: '/social-security-disability-application-kansas-2026', destination: '/social-security-disability-application-kansas-2026-14', permanent: true },
      { source: '/social-security-disability-application-louisiana-2026', destination: '/social-security-disability-application-louisiana-2026-10', permanent: true },
      { source: '/social-security-disability-application-maryland-2026', destination: '/social-security-disability-application-maryland-2026-8', permanent: true },
      { source: '/social-security-disability-application-mississippi-2026', destination: '/social-security-disability-application-mississippi-2026-15', permanent: true },
      { source: '/social-security-disability-application-missouri-2026', destination: '/social-security-disability-application-missouri-2026-17', permanent: true },
      { source: '/social-security-disability-application-montana-2026', destination: '/social-security-disability-application-montana-2026-21', permanent: true },
      { source: '/social-security-disability-application-nebraska-2026', destination: '/social-security-disability-application-nebraska-2026-12', permanent: true },
      { source: '/social-security-disability-application-new-hampshire-2026', destination: '/social-security-disability-application-new-hampshire-2026-9', permanent: true },
      { source: '/social-security-disability-application-north-dakota-2026', destination: '/social-security-disability-application-north-dakota-2026-4', permanent: true },
      { source: '/social-security-disability-application-rhode-island-2026', destination: '/social-security-disability-application-rhode-island-2026-10', permanent: true },
      { source: '/social-security-disability-application-texas-2026', destination: '/social-security-disability-application-texas-2026-7', permanent: true },
      { source: '/social-security-disability-application-virginia-2026', destination: '/social-security-disability-application-virginia-2026-9', permanent: true },
      { source: '/social-security-disability-lawyer-cleveland-2026', destination: '/social-security-disability-lawyer-cleveland-2026-3', permanent: true },
      { source: '/social-security-disability-lawyer-colorado-springs-2026', destination: '/social-security-disability-lawyer-colorado-springs-2026-5', permanent: true },
      { source: '/social-security-disability-lawyer-greensboro-2026', destination: '/social-security-disability-lawyer-greensboro-2026-4', permanent: true },
      { source: '/social-security-disability-lawyer-newark-2026', destination: '/social-security-disability-lawyer-newark-2026-3', permanent: true },
      { source: '/social-security-disability-lawyer-st-louis-2026', destination: '/social-security-disability-lawyer-st-louis-2026-2', permanent: true },
      { source: '/south-carolina-ssdi-application-process-2026', destination: '/south-carolina-ssdi-application-process-2026-9', permanent: true },
      { source: '/ssdi-alj-hearing-tips-2026', destination: '/ssdi-alj-hearing-tips-2026-171', permanent: true },
      { source: '/ssdi-appeal-attorney-albany-2026', destination: '/ssdi-appeal-attorney-albany-2026-2', permanent: true },
      { source: '/ssdi-appeal-attorney-cincinnati-2026', destination: '/ssdi-appeal-attorney-cincinnati-2026-9', permanent: true },
      { source: '/ssdi-appeal-attorney-dallas-2026', destination: '/ssdi-appeal-attorney-dallas-2026-3', permanent: true },
      { source: '/ssdi-appeal-attorney-las-vegas-2026', destination: '/ssdi-appeal-attorney-las-vegas-2026-2', permanent: true },
      { source: '/ssdi-appeal-attorney-memphis-2026', destination: '/ssdi-appeal-attorney-memphis-2026-3', permanent: true },
      { source: '/ssdi-application-help-idaho-2026', destination: '/ssdi-application-help-idaho-2026-2', permanent: true },
      { source: '/ssdi-application-help-michigan-2026', destination: '/ssdi-application-help-michigan-2026-9', permanent: true },
      { source: '/ssdi-application-help-nebraska-2026', destination: '/ssdi-application-help-nebraska-2026-8', permanent: true },
      { source: '/ssdi-application-help-texas-2026', destination: '/ssdi-application-help-texas-2026-7', permanent: true },
      { source: '/ssdi-approval-timeline-alabama-2026', destination: '/ssdi-approval-timeline-alabama-2026-10', permanent: true },
      { source: '/ssdi-approval-timeline-georgia-2026', destination: '/ssdi-approval-timeline-georgia-2026-13', permanent: true },
      { source: '/ssdi-approval-timeline-illinois-2026', destination: '/ssdi-approval-timeline-illinois-2026-20', permanent: true },
      { source: '/ssdi-approval-timeline-kentucky-2026', destination: '/ssdi-approval-timeline-kentucky-2026-4', permanent: true },
      { source: '/ssdi-approval-timeline-maryland-2026', destination: '/ssdi-approval-timeline-maryland-2026-18', permanent: true },
      { source: '/ssdi-approval-timeline-minnesota-2026', destination: '/ssdi-approval-timeline-minnesota-2026-4', permanent: true },
      { source: '/ssdi-approval-timeline-north-carolina-2026', destination: '/ssdi-approval-timeline-north-carolina-2026-15', permanent: true },
      { source: '/ssdi-approval-timeline-oklahoma-2026', destination: '/ssdi-approval-timeline-oklahoma-2026-6', permanent: true },
      { source: '/ssdi-approval-timeline-pennsylvania-2026', destination: '/ssdi-approval-timeline-pennsylvania-2026-7', permanent: true },
      { source: '/ssdi-approval-timeline-tennessee-2026', destination: '/ssdi-approval-timeline-tennessee-2026-6', permanent: true },
      { source: '/ssdi-approval-timeline-texas-2026', destination: '/ssdi-approval-timeline-texas-2026-10', permanent: true },
      { source: '/ssdi-approval-timeline-virginia-2026', destination: '/ssdi-approval-timeline-virginia-2026-15', permanent: true },
      { source: '/ssdi-approval-timeline-washington-2026', destination: '/ssdi-approval-timeline-washington-2026-14', permanent: true },
      { source: '/ssdi-approval-timeline-wisconsin-2026', destination: '/ssdi-approval-timeline-wisconsin-2026-3', permanent: true },
      { source: '/ssdi-attorney-near-me-akron-2026', destination: '/ssdi-attorney-near-me-akron-2026-2', permanent: true },
      { source: '/ssdi-attorney-near-me-phoenix-2026', destination: '/ssdi-attorney-near-me-phoenix-2026-4', permanent: true },
      { source: '/ssdi-attorney-near-me-richmond-2026', destination: '/ssdi-attorney-near-me-richmond-2026-3', permanent: true },
      { source: '/ssdi-attorney-near-me-seattle-2026', destination: '/ssdi-attorney-near-me-seattle-2026-4', permanent: true },
      { source: '/ssdi-benefit-calculator-arizona-2026', destination: '/ssdi-benefit-calculator-arizona-2026-7', permanent: true },
      { source: '/ssdi-benefit-calculator-california-2026', destination: '/ssdi-benefit-calculator-california-2026-4', permanent: true },
      { source: '/ssdi-benefit-calculator-florida-2026', destination: '/ssdi-benefit-calculator-florida-2026-15', permanent: true },
      { source: '/ssdi-benefit-calculator-indiana-2026', destination: '/ssdi-benefit-calculator-indiana-2026-3', permanent: true },
      { source: '/ssdi-benefit-calculator-kentucky-2026', destination: '/ssdi-benefit-calculator-kentucky-2026-2', permanent: true },
      { source: '/ssdi-benefit-calculator-maine-2026', destination: '/ssdi-benefit-calculator-maine-2026-4', permanent: true },
      { source: '/ssdi-benefit-calculator-massachusetts-2026', destination: '/ssdi-benefit-calculator-massachusetts-2026-2', permanent: true },
      { source: '/ssdi-benefit-calculator-michigan-2026', destination: '/ssdi-benefit-calculator-michigan-2026-5', permanent: true },
      { source: '/ssdi-benefit-calculator-minnesota-2026', destination: '/ssdi-benefit-calculator-minnesota-2026-3', permanent: true },
      { source: '/ssdi-benefit-calculator-new-york-2026', destination: '/ssdi-benefit-calculator-new-york-2026-7', permanent: true },
      { source: '/ssdi-benefit-calculator-south-carolina-2026', destination: '/ssdi-benefit-calculator-south-carolina-2026-2', permanent: true },
      { source: '/ssdi-denial-appeal-colorado-2026', destination: '/ssdi-denial-appeal-colorado-2026-2', permanent: true },
      { source: '/ssdi-denial-appeal-iowa-2026', destination: '/ssdi-denial-appeal-iowa-2026-10', permanent: true },
      { source: '/ssdi-denial-appeal-kansas-2026', destination: '/ssdi-denial-appeal-kansas-2026-5', permanent: true },
      { source: '/ssdi-denial-appeal-michigan-2026', destination: '/ssdi-denial-appeal-michigan-2026-9', permanent: true },
      { source: '/ssdi-denial-appeal-nevada-2026', destination: '/ssdi-denial-appeal-nevada-2026-7', permanent: true },
      { source: '/ssdi-denial-appeal-new-jersey-2026', destination: '/ssdi-denial-appeal-new-jersey-2026-5', permanent: true },
      { source: '/ssdi-denial-appeal-pennsylvania-2026', destination: '/ssdi-denial-appeal-pennsylvania-2026-5', permanent: true },
      { source: '/ssdi-denial-appeal-rhode-island-2026', destination: '/ssdi-denial-appeal-rhode-island-2026-7', permanent: true },
      { source: '/ssdi-denial-appeal-south-carolina-2026', destination: '/ssdi-denial-appeal-south-carolina-2026-6', permanent: true },
      { source: '/ssdi-denial-appeal-washington-2026', destination: '/ssdi-denial-appeal-washington-2026-2', permanent: true },
      { source: '/ssdi-for-back-pain-2026', destination: '/ssdi-for-back-pain-2026-32', permanent: true },
      { source: '/ssdi-for-bipolar-disorder-2026', destination: '/ssdi-for-bipolar-disorder-2026-12', permanent: true },
      { source: '/ssdi-for-cancer-2026', destination: '/ssdi-for-cancer-2026-7', permanent: true },
      { source: '/ssdi-for-copd-2026', destination: '/ssdi-for-copd-2026-7', permanent: true },
      { source: '/ssdi-for-crohns-disease-2026', destination: '/ssdi-for-crohns-disease-2026-29', permanent: true },
      { source: '/ssdi-for-diabetes-complications-2026', destination: '/ssdi-for-diabetes-complications-2026-35', permanent: true },
      { source: '/ssdi-for-epilepsy-2026', destination: '/ssdi-for-epilepsy-2026-11', permanent: true },
      { source: '/ssdi-for-lupus-2026', destination: '/ssdi-for-lupus-2026-36', permanent: true },
      { source: '/ssdi-for-multiple-sclerosis-2026', destination: '/ssdi-for-multiple-sclerosis-2026-12', permanent: true },
      { source: '/ssdi-for-rheumatoid-arthritis-2026', destination: '/ssdi-for-rheumatoid-arthritis-2026-15', permanent: true },
      { source: '/ssdi-for-ulcerative-colitis-2026', destination: '/ssdi-for-ulcerative-colitis-2026-9', permanent: true },
      { source: '/ssdi-hearing-attorney-san-francisco-2026', destination: '/ssdi-hearing-attorney-san-francisco-2026-4', permanent: true },
      { source: '/ssdi-hearing-what-to-expect-north-carolina-2026', destination: '/ssdi-hearing-what-to-expect-north-carolina-2026-10', permanent: true },
      { source: '/ssdi-hearing-what-to-expect-texas-2026', destination: '/ssdi-hearing-what-to-expect-texas-2026-5', permanent: true },
      { source: '/ssdi-hearing-what-to-expect-virginia-2026', destination: '/ssdi-hearing-what-to-expect-virginia-2026-2', permanent: true },
      { source: '/ssdi-law-firm-chicago-2026', destination: '/ssdi-law-firm-chicago-2026-2', permanent: true },
      { source: '/ssdi-law-firm-jacksonville-2026', destination: '/ssdi-law-firm-jacksonville-2026-3', permanent: true },
      { source: '/ssdi-law-firm-salt-lake-city-2026', destination: '/ssdi-law-firm-salt-lake-city-2026-3', permanent: true },
      { source: '/ssdi-lawyer-dallas-2026', destination: '/ssdi-lawyer-dallas-2026-2', permanent: true },
      { source: '/ssdi-lawyer-pittsburgh-2026', destination: '/ssdi-lawyer-pittsburgh-2026-2', permanent: true },
      { source: '/ssdi-lawyer-raleigh-2026', destination: '/ssdi-lawyer-raleigh-2026-4', permanent: true },
      { source: '/ssdi-processing-time-georgia-2026', destination: '/ssdi-processing-time-georgia-2026-3', permanent: true },
      { source: '/ssdi-processing-time-indiana-2026', destination: '/ssdi-processing-time-indiana-2026-2', permanent: true },
      { source: '/ssdi-processing-time-kansas-2026', destination: '/ssdi-processing-time-kansas-2026-5', permanent: true },
      { source: '/ssdi-processing-time-maryland-2026', destination: '/ssdi-processing-time-maryland-2026-3', permanent: true },
      { source: '/ssdi-processing-time-michigan-2026', destination: '/ssdi-processing-time-michigan-2026-3', permanent: true },
      { source: '/ssdi-processing-time-north-carolina-2026', destination: '/ssdi-processing-time-north-carolina-2026-17', permanent: true },
      { source: '/ssdi-processing-time-oregon-2026', destination: '/ssdi-processing-time-oregon-2026-11', permanent: true },
      { source: '/ssdi-processing-time-pennsylvania-2026', destination: '/ssdi-processing-time-pennsylvania-2026-15', permanent: true },
      { source: '/ssdi-processing-time-south-carolina-2026', destination: '/ssdi-processing-time-south-carolina-2026-2', permanent: true },
      { source: '/ssdi-processing-time-tennessee-2026', destination: '/ssdi-processing-time-tennessee-2026-13', permanent: true },
      { source: '/ssdi-processing-time-virginia-2026', destination: '/ssdi-processing-time-virginia-2026-6', permanent: true },
      { source: '/ssdi-processing-time-washington-2026', destination: '/ssdi-processing-time-washington-2026-12', permanent: true },
      { source: '/ssdi-processing-time-west-virginia-2026', destination: '/ssdi-processing-time-west-virginia-2026-6', permanent: true },
      { source: '/ssdi-processing-time-wyoming-2026', destination: '/ssdi-processing-time-wyoming-2026-11', permanent: true },
      { source: '/ssdi-reconsideration-california-2026', destination: '/ssdi-reconsideration-california-2026-4', permanent: true },
      { source: '/ssdi-reconsideration-kentucky-2026', destination: '/ssdi-reconsideration-kentucky-2026-6', permanent: true },
      { source: '/ssdi-reconsideration-new-mexico-2026', destination: '/ssdi-reconsideration-new-mexico-2026-3', permanent: true },
      { source: '/ssdi-reconsideration-north-carolina-2026', destination: '/ssdi-reconsideration-north-carolina-2026-6', permanent: true },
      { source: '/ssdi-reconsideration-utah-2026', destination: '/ssdi-reconsideration-utah-2026-2', permanent: true },
      { source: '/ssdi-reconsideration-virginia-2026', destination: '/ssdi-reconsideration-virginia-2026-7', permanent: true },
      { source: '/ssdi-trial-work-period-arkansas-2026', destination: '/ssdi-trial-work-period-arkansas-2026-7', permanent: true },
      { source: '/ssdi-trial-work-period-colorado-2026', destination: '/ssdi-trial-work-period-colorado-2026-6', permanent: true },
      { source: '/ssdi-trial-work-period-florida-2026', destination: '/ssdi-trial-work-period-florida-2026-16', permanent: true },
      { source: '/ssdi-trial-work-period-idaho-2026', destination: '/ssdi-trial-work-period-idaho-2026-5', permanent: true },
      { source: '/ssdi-trial-work-period-illinois-2026', destination: '/ssdi-trial-work-period-illinois-2026-6', permanent: true },
      { source: '/ssdi-trial-work-period-indiana-2026', destination: '/ssdi-trial-work-period-indiana-2026-2', permanent: true },
      { source: '/ssdi-trial-work-period-iowa-2026', destination: '/ssdi-trial-work-period-iowa-2026-2', permanent: true },
      { source: '/ssdi-trial-work-period-kentucky-2026', destination: '/ssdi-trial-work-period-kentucky-2026-11', permanent: true },
      { source: '/ssdi-trial-work-period-michigan-2026', destination: '/ssdi-trial-work-period-michigan-2026-2', permanent: true },
      { source: '/ssdi-trial-work-period-missouri-2026', destination: '/ssdi-trial-work-period-missouri-2026-7', permanent: true },
      { source: '/ssdi-trial-work-period-new-york-2026', destination: '/ssdi-trial-work-period-new-york-2026-26', permanent: true },
      { source: '/ssdi-trial-work-period-virginia-2026', destination: '/ssdi-trial-work-period-virginia-2026-4', permanent: true },
      { source: '/ssdi-trial-work-period-washington-2026', destination: '/ssdi-trial-work-period-washington-2026-14', permanent: true },
      { source: '/ssdi-trial-work-period-wisconsin-2026', destination: '/ssdi-trial-work-period-wisconsin-2026-8', permanent: true },
      { source: '/ssdi-work-credits-california-2026', destination: '/ssdi-work-credits-california-2026-10', permanent: true },
      { source: '/ssdi-work-credits-louisiana-2026', destination: '/ssdi-work-credits-louisiana-2026-5', permanent: true },
      { source: '/ssdi-work-credits-maine-2026', destination: '/ssdi-work-credits-maine-2026-4', permanent: true },
      { source: '/ssdi-work-credits-texas-2026', destination: '/ssdi-work-credits-texas-2026-2', permanent: true },
      { source: '/ssdi-work-credits-wyoming-2026', destination: '/ssdi-work-credits-wyoming-2026-27', permanent: true },
      { source: '/texas-ssdi-application-process-2026', destination: '/texas-ssdi-application-process-2026-13', permanent: true },
      { source: '/toledo-ssdi-representation-2026', destination: '/toledo-ssdi-representation-2026-3', permanent: true },
      { source: '/vermont-ssdi-application-process-2026', destination: '/vermont-ssdi-application-process-2026-14', permanent: true },
      { source: '/washington-ssdi-application-process-2026', destination: '/washington-ssdi-application-process-2026-6', permanent: true },
      { source: '/west-virginia-ssdi-application-process-2026', destination: '/west-virginia-ssdi-application-process-2026-22', permanent: true },
      { source: '/working-part-time-on-disability-california-2026', destination: '/working-part-time-on-disability-california-2026-3', permanent: true },
      { source: '/working-part-time-on-disability-georgia-2026', destination: '/working-part-time-on-disability-georgia-2026-6', permanent: true },
      { source: '/working-part-time-on-disability-idaho-2026', destination: '/working-part-time-on-disability-idaho-2026-6', permanent: true },
      { source: '/working-part-time-on-disability-kansas-2026', destination: '/working-part-time-on-disability-kansas-2026-2', permanent: true },
      { source: '/working-part-time-on-disability-maine-2026', destination: '/working-part-time-on-disability-maine-2026-3', permanent: true },
      { source: '/working-part-time-on-disability-missouri-2026', destination: '/working-part-time-on-disability-missouri-2026-2', permanent: true },
      { source: '/working-part-time-on-disability-new-jersey-2026', destination: '/working-part-time-on-disability-new-jersey-2026-10', permanent: true },
      { source: '/working-part-time-on-disability-pennsylvania-2026', destination: '/working-part-time-on-disability-pennsylvania-2026-2', permanent: true },
      { source: '/working-part-time-on-disability-south-dakota-2026', destination: '/working-part-time-on-disability-south-dakota-2026-2', permanent: true },
      { source: '/working-part-time-on-disability-vermont-2026', destination: '/working-part-time-on-disability-vermont-2026-6', permanent: true },
      // ── SEO P0 2026-06-18: FPP twin consolidation — 301 base → -N earner (the URL Google ranked) ──
      { source: '/bad-faith-insurance-attorney-west-palm-beach-2026', destination: '/bad-faith-insurance-attorney-west-palm-beach-2026-3', permanent: true },
      { source: '/boca-raton-mold-damage-lawyer-2026', destination: '/boca-raton-mold-damage-lawyer-2026-3', permanent: true },
      { source: '/flood-damage-lawyer-sarasota-2026', destination: '/flood-damage-lawyer-sarasota-2026-5', permanent: true },
      { source: '/flooding-insurance-claim-tampa-2026', destination: '/flooding-insurance-claim-tampa-2026-2', permanent: true },
      { source: '/hail-damage-insurance-jacksonville-2026', destination: '/hail-damage-insurance-jacksonville-2026-2', permanent: true },
      { source: '/hurricane-damage-attorney-naples-2026', destination: '/hurricane-damage-attorney-naples-2026-2', permanent: true },
      { source: '/hurricane-damage-attorney-west-palm-beach-2026', destination: '/hurricane-damage-attorney-west-palm-beach-2026-7', permanent: true },
      { source: '/hurricane-damage-claim-miami-2026', destination: '/hurricane-damage-claim-miami-2026-3', permanent: true },
      { source: '/hurricane-damage-claim-pensacola-2026', destination: '/hurricane-damage-claim-pensacola-2026-2', permanent: true },
      { source: '/insurance-denied-mold-claim-florida-2026', destination: '/insurance-denied-mold-claim-florida-2026-64', permanent: true },
      { source: '/insurance-denied-mold-claim-west-palm-beach-2026', destination: '/insurance-denied-mold-claim-west-palm-beach-2026-5', permanent: true },
      { source: '/miami-water-damage-lawyer-2026', destination: '/miami-water-damage-lawyer-2026-4', permanent: true },
      { source: '/mold-damage-lawyer-miami-2026', destination: '/mold-damage-lawyer-miami-2026-4', permanent: true },
      { source: '/mold-remediation-insurance-lawyer-boca-raton-2026', destination: '/mold-remediation-insurance-lawyer-boca-raton-2026-4', permanent: true },
      { source: '/pensacola-property-damage-attorney-2026', destination: '/pensacola-property-damage-attorney-2026-5', permanent: true },
      { source: '/property-damage-lawyer-boca-raton-2026', destination: '/property-damage-lawyer-boca-raton-2026-2', permanent: true },
      { source: '/property-damage-lawyer-orlando-2026', destination: '/property-damage-lawyer-orlando-2026-5', permanent: true },
      { source: '/property-damage-lawyer-pensacola-2026', destination: '/property-damage-lawyer-pensacola-2026-3', permanent: true },
      { source: '/property-damage-lawyer-west-palm-beach-2026', destination: '/property-damage-lawyer-west-palm-beach-2026-4', permanent: true },
      { source: '/property-insurance-claim-process-tampa-2026', destination: '/property-insurance-claim-process-tampa-2026-2', permanent: true },
      { source: '/public-adjuster-vs-lawyer-boca-raton-2026', destination: '/public-adjuster-vs-lawyer-boca-raton-2026-4', permanent: true },
      { source: '/roof-leak-insurance-claim-florida-2026', destination: '/roof-leak-insurance-claim-florida-2026-34', permanent: true },
      { source: '/sarasota-hurricane-insurance-lawyer-2026', destination: '/sarasota-hurricane-insurance-lawyer-2026-2', permanent: true },
      { source: '/sarasota-property-damage-attorney-2026', destination: '/sarasota-property-damage-attorney-2026-3', permanent: true },
      { source: '/st-petersburg-water-damage-lawyer-2026', destination: '/st-petersburg-water-damage-lawyer-2026-2', permanent: true },
      { source: '/storm-damage-insurance-claim-florida-2026', destination: '/storm-damage-insurance-claim-florida-2026-7', permanent: true },
      { source: '/toxic-mold-insurance-claim-lawyer-orlando-2026', destination: '/toxic-mold-insurance-claim-lawyer-orlando-2026-8', permanent: true },
      { source: '/toxic-mold-lawsuit-boca-raton-2026', destination: '/toxic-mold-lawsuit-boca-raton-2026-7', permanent: true },
      { source: '/toxic-mold-lawsuit-gainesville-2026', destination: '/toxic-mold-lawsuit-gainesville-2026-3', permanent: true },
      { source: '/toxic-mold-lawsuit-jacksonville-2026', destination: '/toxic-mold-lawsuit-jacksonville-2026-4', permanent: true },
      { source: '/underpaid-insurance-claim-boca-raton-2026', destination: '/underpaid-insurance-claim-boca-raton-2026-2', permanent: true },
      { source: '/water-damage-attorney-miami-2026', destination: '/water-damage-attorney-miami-2026-5', permanent: true },
      { source: '/wind-damage-insurance-attorney-coral-springs-2026', destination: '/wind-damage-insurance-attorney-coral-springs-2026-4', permanent: true },
      { source: '/wind-damage-insurance-attorney-miami-2026', destination: '/wind-damage-insurance-attorney-miami-2026-7', permanent: true },
      // Removed former team members — bio pages redirect to /team
      { source: '/romina-murias', destination: '/team', permanent: true },
      { source: '/team/romina-murias', destination: '/team', permanent: true },
      { source: '/kellei-johnson', destination: '/team', permanent: true },
      { source: '/team/kellei-johnson', destination: '/team', permanent: true },
      { source: '/monica-abay', destination: '/team', permanent: true },
      { source: '/team/monica-abay', destination: '/team', permanent: true },
      { source: '/yonel-mesa', destination: '/team', permanent: true },
      { source: '/team/yonel-mesa', destination: '/team', permanent: true },
      { source: '/brett-conger-esq', destination: '/team', permanent: true },
      { source: '/team/brett-conger-esq', destination: '/team', permanent: true },

      // ── AHS consolidation (2,568 thin city pages → 1 hub) ──
      // Redirects all AHS article variants to the privacy torts landing page.
      // The privacy torts page (/american-home-shield-privacy-torts) is a static
      // route so it won't be caught by these patterns.

      // ahs-* (61+ pages: ahs-claim-denial-*, ahs-guide-*, ahs-coverage-*, etc.)
      { source: '/ahs-:slug*', destination: '/american-home-shield-privacy-torts', permanent: true },

      // american-home-shield-claim-* (807 pages)
      { source: '/american-home-shield-claim-:slug*', destination: '/american-home-shield-privacy-torts', permanent: true },

      // american-home-shield-guide-* and guide-to-american-* and guide-american-home-* (2,302 pages)
      { source: '/american-home-shield-guide-:slug*', destination: '/american-home-shield-privacy-torts', permanent: true },
      { source: '/guide-to-american-:slug*', destination: '/american-home-shield-privacy-torts', permanent: true },
      { source: '/guide-american-home-:slug*', destination: '/american-home-shield-privacy-torts', permanent: true },

      // american-home-shield-denied-* (denied claims)
      { source: '/american-home-shield-denied-:slug*', destination: '/american-home-shield-privacy-torts', permanent: true },

      // american-home-shield-rights-* and your-rights-after-american-*
      { source: '/american-home-shield-rights-:slug*', destination: '/american-home-shield-privacy-torts', permanent: true },
      { source: '/your-rights-:slug(.*american-home-shield.*)', destination: '/american-home-shield-privacy-torts', permanent: true },
      { source: '/your-guide-to-:slug(.*american-home-shield.*)', destination: '/american-home-shield-privacy-torts', permanent: true },

      // american-home-shield-lawsuit-*, american-home-shield-sue-*
      { source: '/american-home-shield-lawsuit-:slug*', destination: '/american-home-shield-privacy-torts', permanent: true },
      { source: '/american-home-shield-sue-:slug*', destination: '/american-home-shield-privacy-torts', permanent: true },
      { source: '/sue-american-home-:slug*', destination: '/american-home-shield-privacy-torts', permanent: true },

      // american-home-shield-coverage-*
      { source: '/american-home-shield-coverage-:slug*', destination: '/american-home-shield-privacy-torts', permanent: true },

      // legal-guide-american-*, legal-american-home-*
      { source: '/legal-guide-american-:slug*', destination: '/american-home-shield-privacy-torts', permanent: true },
      { source: '/legal-american-home-:slug*', destination: '/american-home-shield-privacy-torts', permanent: true },

      // ── Allstate cannibalization fix (2026-04-01) ──
      // Texas variant competes with main Allstate page — LLG doesn't practice in TX.
      // Consolidate 1,162 impr into the main page at pos 3.9
      { source: '/allstate-denied-my-roof-claim-texas', destination: '/allstate-denied-my-roof-claim', permanent: true },

      // ── Personal Injury section (2026-04-13) ──
      // Nav link in Strapi points to /personal-injury-attorneys → redirect to new static PI page
      { source: '/personal-injury-attorneys', destination: '/personal-injury', permanent: true },


      // ── FPP suffix-duplicate 301s (284 pages, 2026-04-18) ──
      { source: '/allstate-claim-denial-attorney-2026-1', destination: '/allstate-claim-denial-attorney-2026', permanent: true },
      { source: '/allstate-insurance-denied-claim-florida-2026-1', destination: '/allstate-insurance-denied-claim-florida-2026', permanent: true },
      { source: '/allstate-roof-claim-denied-texas-2026-1', destination: '/allstate-roof-claim-denied-texas-2026', permanent: true },
      { source: '/bad-faith-insurance-attorney-orlando-2026-1', destination: '/bad-faith-insurance-attorney-orlando-2026', permanent: true },
      { source: '/bad-faith-insurance-attorney-st-petersburg-2026-1', destination: '/bad-faith-insurance-attorney-st-petersburg-2026', permanent: true },
      { source: '/bad-faith-insurance-attorney-st-petersburg-2026-2', destination: '/bad-faith-insurance-attorney-st-petersburg-2026', permanent: true },
      { source: '/bad-faith-insurance-attorney-tampa-2026-1', destination: '/bad-faith-insurance-attorney-tampa-2026', permanent: true },
      { source: '/black-mold-insurance-claim-hollywood-2026-1', destination: '/black-mold-insurance-claim-hollywood-2026', permanent: true },
      { source: '/boca-raton-fire-damage-attorney-2026-1', destination: '/boca-raton-fire-damage-attorney-2026', permanent: true },
      { source: '/boca-raton-hurricane-insurance-lawyer-2026-2', destination: '/boca-raton-hurricane-insurance-lawyer-2026', permanent: true },
      { source: '/boca-raton-water-damage-insurance-lawyer-2026-3', destination: '/boca-raton-water-damage-insurance-lawyer-2026', permanent: true },
      { source: '/boca-raton-water-damage-lawyer-2026-1', destination: '/boca-raton-water-damage-lawyer-2026', permanent: true },
      { source: '/burst-pipe-insurance-claim-coral-springs-2026-1', destination: '/burst-pipe-insurance-claim-coral-springs-2026', permanent: true },
      { source: '/burst-pipe-insurance-claim-fort-lauderdale-2026-1', destination: '/burst-pipe-insurance-claim-fort-lauderdale-2026', permanent: true },
      { source: '/coral-springs-hurricane-insurance-lawyer-2026-1', destination: '/coral-springs-hurricane-insurance-lawyer-2026', permanent: true },
      { source: '/coral-springs-hurricane-insurance-lawyer-2026-2', destination: '/coral-springs-hurricane-insurance-lawyer-2026', permanent: true },
      { source: '/coral-springs-storm-claim-lawyer-2026-1', destination: '/coral-springs-storm-claim-lawyer-2026', permanent: true },
      { source: '/denied-insurance-claim-lawyer-coral-springs-2026-1', destination: '/denied-insurance-claim-lawyer-coral-springs-2026', permanent: true },
      { source: '/denied-insurance-claim-lawyer-jacksonville-2026-1', destination: '/denied-insurance-claim-lawyer-jacksonville-2026', permanent: true },
      { source: '/denied-insurance-claim-lawyer-miami-2026-3', destination: '/denied-insurance-claim-lawyer-miami-2026', permanent: true },
      { source: '/denied-insurance-claim-lawyer-naples-2026-1', destination: '/denied-insurance-claim-lawyer-naples-2026', permanent: true },
      { source: '/denied-insurance-claim-lawyer-pembroke-pines-2026-1', destination: '/denied-insurance-claim-lawyer-pembroke-pines-2026', permanent: true },
      { source: '/denied-insurance-claim-lawyer-st-petersburg-2026-1', destination: '/denied-insurance-claim-lawyer-st-petersburg-2026', permanent: true },
      { source: '/denied-insurance-claim-lawyer-st-petersburg-2026-4', destination: '/denied-insurance-claim-lawyer-st-petersburg-2026', permanent: true },
      { source: '/denied-insurance-claim-lawyer-tampa-2026-1', destination: '/denied-insurance-claim-lawyer-tampa-2026', permanent: true },
      { source: '/documenting-property-damage-florida-2026-1', destination: '/documenting-property-damage-florida-2026', permanent: true },
      { source: '/documenting-property-damage-florida-2026-4', destination: '/documenting-property-damage-florida-2026', permanent: true },
      { source: '/fight-kin-insurance-denial-florida-2026-1', destination: '/fight-kin-insurance-denial-florida-2026', permanent: true },
      { source: '/fire-damage-claim-coral-springs-2026-1', destination: '/fire-damage-claim-coral-springs-2026', permanent: true },
      { source: '/fire-damage-claim-gainesville-2026-1', destination: '/fire-damage-claim-gainesville-2026', permanent: true },
      { source: '/fire-damage-claim-hollywood-2026-1', destination: '/fire-damage-claim-hollywood-2026', permanent: true },
      { source: '/fire-damage-claim-miami-2026-1', destination: '/fire-damage-claim-miami-2026', permanent: true },
      { source: '/fire-damage-claim-naples-2026-1', destination: '/fire-damage-claim-naples-2026', permanent: true },
      { source: '/fire-damage-claim-orlando-2026-1', destination: '/fire-damage-claim-orlando-2026', permanent: true },
      { source: '/flood-damage-lawyer-coral-springs-2026-2', destination: '/flood-damage-lawyer-coral-springs-2026', permanent: true },
      { source: '/flood-damage-lawyer-fort-lauderdale-2026-1', destination: '/flood-damage-lawyer-fort-lauderdale-2026', permanent: true },
      { source: '/flood-damage-lawyer-fort-lauderdale-2026-2', destination: '/flood-damage-lawyer-fort-lauderdale-2026', permanent: true },
      { source: '/flood-damage-lawyer-hialeah-2026-1', destination: '/flood-damage-lawyer-hialeah-2026', permanent: true },
      { source: '/flood-damage-lawyer-hollywood-2026-1', destination: '/flood-damage-lawyer-hollywood-2026', permanent: true },
      { source: '/flood-damage-lawyer-hollywood-2026-2', destination: '/flood-damage-lawyer-hollywood-2026', permanent: true },
      { source: '/flood-damage-lawyer-jacksonville-2026-2', destination: '/flood-damage-lawyer-jacksonville-2026', permanent: true },
      { source: '/flood-damage-lawyer-jacksonville-2026-3', destination: '/flood-damage-lawyer-jacksonville-2026', permanent: true },
      { source: '/flood-damage-lawyer-miami-2026-1', destination: '/flood-damage-lawyer-miami-2026', permanent: true },
      { source: '/flood-damage-lawyer-orlando-2026-1', destination: '/flood-damage-lawyer-orlando-2026', permanent: true },
      { source: '/flood-damage-lawyer-orlando-2026-7', destination: '/flood-damage-lawyer-orlando-2026', permanent: true },
      { source: '/flood-damage-lawyer-pembroke-pines-2026-2', destination: '/flood-damage-lawyer-pembroke-pines-2026', permanent: true },
      { source: '/flood-damage-lawyer-port-st-lucie-2026-1', destination: '/flood-damage-lawyer-port-st-lucie-2026', permanent: true },
      { source: '/flood-damage-lawyer-port-st-lucie-2026-2', destination: '/flood-damage-lawyer-port-st-lucie-2026', permanent: true },
      { source: '/flood-damage-lawyer-port-st-lucie-2026-5', destination: '/flood-damage-lawyer-port-st-lucie-2026', permanent: true },
      { source: '/flood-damage-lawyer-sarasota-2026-1', destination: '/flood-damage-lawyer-sarasota-2026', permanent: true },
      { source: '/flood-damage-lawyer-sarasota-2026-4', destination: '/flood-damage-lawyer-sarasota-2026', permanent: true },
      { source: '/flood-damage-lawyer-tampa-2026-1', destination: '/flood-damage-lawyer-tampa-2026', permanent: true },
      { source: '/flooding-insurance-claim-boca-raton-2026-1', destination: '/flooding-insurance-claim-boca-raton-2026', permanent: true },
      { source: '/flooding-insurance-claim-boca-raton-2026-2', destination: '/flooding-insurance-claim-boca-raton-2026', permanent: true },
      { source: '/flooding-insurance-claim-coral-springs-2026-1', destination: '/flooding-insurance-claim-coral-springs-2026', permanent: true },
      { source: '/flooding-insurance-claim-fort-lauderdale-2026-1', destination: '/flooding-insurance-claim-fort-lauderdale-2026', permanent: true },
      { source: '/flooding-insurance-claim-miami-2026-4', destination: '/flooding-insurance-claim-miami-2026', permanent: true },
      { source: '/flooding-insurance-claim-naples-2026-1', destination: '/flooding-insurance-claim-naples-2026', permanent: true },
      { source: '/flooding-insurance-claim-orlando-2026-1', destination: '/flooding-insurance-claim-orlando-2026', permanent: true },
      { source: '/fort-lauderdale-hurricane-insurance-lawyer-2026-1', destination: '/fort-lauderdale-hurricane-insurance-lawyer-2026', permanent: true },
      { source: '/fort-lauderdale-property-damage-attorney-2026-5', destination: '/fort-lauderdale-property-damage-attorney-2026', permanent: true },
      { source: '/fort-lauderdale-property-damage-attorney-2026-9', destination: '/fort-lauderdale-property-damage-attorney-2026', permanent: true },
      { source: '/fort-lauderdale-storm-claim-lawyer-2026-1', destination: '/fort-lauderdale-storm-claim-lawyer-2026', permanent: true },
      { source: '/fort-lauderdale-water-damage-insurance-lawyer-2026-3', destination: '/fort-lauderdale-water-damage-insurance-lawyer-2026', permanent: true },
      { source: '/fort-lauderdale-water-damage-insurance-lawyer-2026-4', destination: '/fort-lauderdale-water-damage-insurance-lawyer-2026', permanent: true },
      { source: '/fort-lauderdale-water-damage-lawyer-2026-1', destination: '/fort-lauderdale-water-damage-lawyer-2026', permanent: true },
      { source: '/gainesville-hurricane-insurance-lawyer-2026-1', destination: '/gainesville-hurricane-insurance-lawyer-2026', permanent: true },
      { source: '/hail-damage-insurance-boca-raton-2026-1', destination: '/hail-damage-insurance-boca-raton-2026', permanent: true },
      { source: '/hail-damage-insurance-port-st-lucie-2026-1', destination: '/hail-damage-insurance-port-st-lucie-2026', permanent: true },
      { source: '/hail-damage-insurance-tampa-2026-6', destination: '/hail-damage-insurance-tampa-2026', permanent: true },
      { source: '/hail-damage-insurance-west-palm-beach-2026-1', destination: '/hail-damage-insurance-west-palm-beach-2026', permanent: true },
      { source: '/hail-damage-insurance-west-palm-beach-2026-3', destination: '/hail-damage-insurance-west-palm-beach-2026', permanent: true },
      { source: '/hialeah-hurricane-insurance-lawyer-2026-1', destination: '/hialeah-hurricane-insurance-lawyer-2026', permanent: true },
      { source: '/hialeah-storm-claim-lawyer-2026-7', destination: '/hialeah-storm-claim-lawyer-2026', permanent: true },
      { source: '/hollywood-fire-damage-attorney-2026-1', destination: '/hollywood-fire-damage-attorney-2026', permanent: true },
      { source: '/hollywood-hurricane-insurance-lawyer-2026-1', destination: '/hollywood-hurricane-insurance-lawyer-2026', permanent: true },
      { source: '/hollywood-mold-damage-lawyer-2026-1', destination: '/hollywood-mold-damage-lawyer-2026', permanent: true },
      { source: '/hollywood-property-damage-attorney-2026-1', destination: '/hollywood-property-damage-attorney-2026', permanent: true },
      { source: '/house-fire-insurance-claim-denied-florida-2026-46', destination: '/house-fire-insurance-claim-denied-florida-2026', permanent: true },
      { source: '/how-to-file-property-damage-claim-florida-2026-11', destination: '/how-to-file-property-damage-claim-florida-2026', permanent: true },
      { source: '/how-to-file-property-damage-claim-florida-2026-14', destination: '/how-to-file-property-damage-claim-florida-2026', permanent: true },
      { source: '/hurricane-damage-attorney-coral-springs-2026-1', destination: '/hurricane-damage-attorney-coral-springs-2026', permanent: true },
      { source: '/hurricane-damage-attorney-gainesville-2026-5', destination: '/hurricane-damage-attorney-gainesville-2026', permanent: true },
      { source: '/hurricane-damage-attorney-miami-2026-1', destination: '/hurricane-damage-attorney-miami-2026', permanent: true },
      { source: '/hurricane-damage-attorney-naples-2026-1', destination: '/hurricane-damage-attorney-naples-2026', permanent: true },
      { source: '/hurricane-damage-attorney-orlando-2026-1', destination: '/hurricane-damage-attorney-orlando-2026', permanent: true },
      { source: '/hurricane-damage-attorney-pembroke-pines-2026-2', destination: '/hurricane-damage-attorney-pembroke-pines-2026', permanent: true },
      { source: '/hurricane-damage-attorney-pembroke-pines-2026-4', destination: '/hurricane-damage-attorney-pembroke-pines-2026', permanent: true },
      { source: '/hurricane-damage-attorney-pensacola-2026-2', destination: '/hurricane-damage-attorney-pensacola-2026', permanent: true },
      { source: '/hurricane-damage-attorney-pensacola-2026-3', destination: '/hurricane-damage-attorney-pensacola-2026', permanent: true },
      { source: '/hurricane-damage-attorney-sarasota-2026-1', destination: '/hurricane-damage-attorney-sarasota-2026', permanent: true },
      { source: '/hurricane-damage-claim-fort-lauderdale-2026-2', destination: '/hurricane-damage-claim-fort-lauderdale-2026', permanent: true },
      { source: '/hurricane-damage-claim-gainesville-2026-2', destination: '/hurricane-damage-claim-gainesville-2026', permanent: true },
      { source: '/hurricane-damage-claim-hialeah-2026-1', destination: '/hurricane-damage-claim-hialeah-2026', permanent: true },
      { source: '/hurricane-damage-claim-miami-2026-1', destination: '/hurricane-damage-claim-miami-2026', permanent: true },
      { source: '/hurricane-damage-claim-port-st-lucie-2026-1', destination: '/hurricane-damage-claim-port-st-lucie-2026', permanent: true },
      { source: '/hurricane-damage-claim-west-palm-beach-2026-1', destination: '/hurricane-damage-claim-west-palm-beach-2026', permanent: true },
      { source: '/insurance-bad-faith-jacksonville-florida-2026-1', destination: '/insurance-bad-faith-jacksonville-florida-2026', permanent: true },
      { source: '/insurance-bad-faith-st-petersburg-florida-2026-1', destination: '/insurance-bad-faith-st-petersburg-florida-2026', permanent: true },
      { source: '/insurance-claim-attorney-coral-springs-2026-1', destination: '/insurance-claim-attorney-coral-springs-2026', permanent: true },
      { source: '/insurance-claim-attorney-hollywood-2026-1', destination: '/insurance-claim-attorney-hollywood-2026', permanent: true },
      { source: '/insurance-claim-attorney-jacksonville-2026-1', destination: '/insurance-claim-attorney-jacksonville-2026', permanent: true },
      { source: '/insurance-claim-attorney-miami-2026-1', destination: '/insurance-claim-attorney-miami-2026', permanent: true },
      { source: '/insurance-claim-attorney-naples-2026-1', destination: '/insurance-claim-attorney-naples-2026', permanent: true },
      { source: '/insurance-claim-attorney-orlando-2026-1', destination: '/insurance-claim-attorney-orlando-2026', permanent: true },
      { source: '/insurance-claim-attorney-orlando-2026-2', destination: '/insurance-claim-attorney-orlando-2026', permanent: true },
      { source: '/insurance-claim-attorney-tampa-2026-1', destination: '/insurance-claim-attorney-tampa-2026', permanent: true },
      { source: '/insurance-claim-attorney-west-palm-beach-2026-1', destination: '/insurance-claim-attorney-west-palm-beach-2026', permanent: true },
      { source: '/insurance-company-delay-tactics-florida-2026-27', destination: '/insurance-company-delay-tactics-florida-2026', permanent: true },
      { source: '/insurance-denied-mold-claim-florida-2026-1', destination: '/insurance-denied-mold-claim-florida-2026', permanent: true },
      { source: '/insurance-denied-mold-claim-florida-2026-21', destination: '/insurance-denied-mold-claim-florida-2026', permanent: true },
      { source: '/insurance-denied-mold-claim-florida-2026-32', destination: '/insurance-denied-mold-claim-florida-2026', permanent: true },
      { source: '/insurance-denied-mold-claim-florida-2026-9', destination: '/insurance-denied-mold-claim-florida-2026', permanent: true },
      { source: '/insurance-denied-mold-claim-naples-2026-1', destination: '/insurance-denied-mold-claim-naples-2026', permanent: true },
      { source: '/insurance-denied-mold-claim-orlando-2026-3', destination: '/insurance-denied-mold-claim-orlando-2026', permanent: true },
      { source: '/insurance-denied-mold-claim-pembroke-pines-2026-1', destination: '/insurance-denied-mold-claim-pembroke-pines-2026', permanent: true },
      { source: '/insurance-denied-mold-claim-pembroke-pines-2026-2', destination: '/insurance-denied-mold-claim-pembroke-pines-2026', permanent: true },
      { source: '/insurance-denied-mold-claim-west-palm-beach-2026-4', destination: '/insurance-denied-mold-claim-west-palm-beach-2026', permanent: true },
      { source: '/insurance-denied-mold-claim-west-palm-beach-2026-6', destination: '/insurance-denied-mold-claim-west-palm-beach-2026', permanent: true },
      { source: '/insurance-denied-water-damage-claim-florida-2026-18', destination: '/insurance-denied-water-damage-claim-florida-2026', permanent: true },
      { source: '/insurance-denied-water-damage-claim-florida-2026-3', destination: '/insurance-denied-water-damage-claim-florida-2026', permanent: true },
      { source: '/insurance-denied-water-damage-claim-florida-2026-30', destination: '/insurance-denied-water-damage-claim-florida-2026', permanent: true },
      { source: '/insurance-denied-water-damage-claim-florida-2026-31', destination: '/insurance-denied-water-damage-claim-florida-2026', permanent: true },
      { source: '/insurance-denied-water-damage-claim-florida-2026-35', destination: '/insurance-denied-water-damage-claim-florida-2026', permanent: true },
      { source: '/jacksonville-storm-claim-lawyer-2026-1', destination: '/jacksonville-storm-claim-lawyer-2026', permanent: true },
      { source: '/jacksonville-storm-claim-lawyer-2026-7', destination: '/jacksonville-storm-claim-lawyer-2026', permanent: true },
      { source: '/jacksonville-water-damage-lawyer-2026-1', destination: '/jacksonville-water-damage-lawyer-2026', permanent: true },
      { source: '/miami-fire-damage-attorney-2026-1', destination: '/miami-fire-damage-attorney-2026', permanent: true },
      { source: '/miami-mold-damage-attorney-2026-2', destination: '/miami-mold-damage-attorney-2026', permanent: true },
      { source: '/miami-mold-damage-lawyer-2026-1', destination: '/miami-mold-damage-lawyer-2026', permanent: true },
      { source: '/miami-property-damage-attorney-2026-1', destination: '/miami-property-damage-attorney-2026', permanent: true },
      { source: '/miami-storm-claim-lawyer-2026-5', destination: '/miami-storm-claim-lawyer-2026', permanent: true },
      { source: '/miami-water-damage-lawyer-2026-1', destination: '/miami-water-damage-lawyer-2026', permanent: true },
      { source: '/mold-coverage-dispute-hollywood-2026-1', destination: '/mold-coverage-dispute-hollywood-2026', permanent: true },
      { source: '/mold-coverage-dispute-hollywood-2026-3', destination: '/mold-coverage-dispute-hollywood-2026', permanent: true },
      { source: '/mold-coverage-dispute-orlando-2026-1', destination: '/mold-coverage-dispute-orlando-2026', permanent: true },
      { source: '/mold-coverage-dispute-pembroke-pines-2026-1', destination: '/mold-coverage-dispute-pembroke-pines-2026', permanent: true },
      { source: '/mold-damage-attorney-hollywood-2026-1', destination: '/mold-damage-attorney-hollywood-2026', permanent: true },
      { source: '/mold-damage-attorney-miami-2026-1', destination: '/mold-damage-attorney-miami-2026', permanent: true },
      { source: '/mold-damage-insurance-claim-hollywood-2026-2', destination: '/mold-damage-insurance-claim-hollywood-2026', permanent: true },
      { source: '/mold-damage-insurance-claim-hollywood-2026-3', destination: '/mold-damage-insurance-claim-hollywood-2026', permanent: true },
      { source: '/mold-damage-insurance-claim-pembroke-pines-2026-2', destination: '/mold-damage-insurance-claim-pembroke-pines-2026', permanent: true },
      { source: '/mold-damage-lawyer-boca-raton-2026-7', destination: '/mold-damage-lawyer-boca-raton-2026', permanent: true },
      { source: '/mold-damage-lawyer-miami-2026-1', destination: '/mold-damage-lawyer-miami-2026', permanent: true },
      { source: '/mold-damage-lawyer-orlando-2026-1', destination: '/mold-damage-lawyer-orlando-2026', permanent: true },
      { source: '/mold-damage-lawyer-pensacola-2026-4', destination: '/mold-damage-lawyer-pensacola-2026', permanent: true },
      { source: '/mold-insurance-claim-denied-naples-2026-3', destination: '/mold-insurance-claim-denied-naples-2026', permanent: true },
      { source: '/mold-insurance-claim-denied-naples-2026-4', destination: '/mold-insurance-claim-denied-naples-2026', permanent: true },
      { source: '/mold-insurance-claim-denied-port-st-lucie-2026-3', destination: '/mold-insurance-claim-denied-port-st-lucie-2026', permanent: true },
      { source: '/mold-remediation-insurance-lawyer-boca-raton-2026-1', destination: '/mold-remediation-insurance-lawyer-boca-raton-2026', permanent: true },
      { source: '/mold-remediation-insurance-lawyer-hollywood-2026-1', destination: '/mold-remediation-insurance-lawyer-hollywood-2026', permanent: true },
      { source: '/mold-remediation-insurance-lawyer-orlando-2026-1', destination: '/mold-remediation-insurance-lawyer-orlando-2026', permanent: true },
      { source: '/mold-remediation-insurance-lawyer-pembroke-pines-2026-1', destination: '/mold-remediation-insurance-lawyer-pembroke-pines-2026', permanent: true },
      { source: '/orlando-fire-damage-attorney-2026-1', destination: '/orlando-fire-damage-attorney-2026', permanent: true },
      { source: '/orlando-hurricane-insurance-lawyer-2026-1', destination: '/orlando-hurricane-insurance-lawyer-2026', permanent: true },
      { source: '/orlando-hurricane-insurance-lawyer-2026-4', destination: '/orlando-hurricane-insurance-lawyer-2026', permanent: true },
      { source: '/orlando-mold-damage-lawyer-2026-3', destination: '/orlando-mold-damage-lawyer-2026', permanent: true },
      { source: '/orlando-water-damage-lawyer-2026-1', destination: '/orlando-water-damage-lawyer-2026', permanent: true },
      { source: '/pembroke-pines-hurricane-insurance-lawyer-2026-1', destination: '/pembroke-pines-hurricane-insurance-lawyer-2026', permanent: true },
      { source: '/pembroke-pines-storm-claim-lawyer-2026-5', destination: '/pembroke-pines-storm-claim-lawyer-2026', permanent: true },
      { source: '/pembroke-pines-water-damage-insurance-lawyer-2026-5', destination: '/pembroke-pines-water-damage-insurance-lawyer-2026', permanent: true },
      { source: '/pensacola-property-damage-attorney-2026-1', destination: '/pensacola-property-damage-attorney-2026', permanent: true },
      { source: '/pensacola-property-damage-attorney-2026-2', destination: '/pensacola-property-damage-attorney-2026', permanent: true },
      { source: '/pensacola-water-damage-lawyer-2026-3', destination: '/pensacola-water-damage-lawyer-2026', permanent: true },
      { source: '/plumbing-leak-insurance-florida-2026-15', destination: '/plumbing-leak-insurance-florida-2026', permanent: true },
      { source: '/plumbing-leak-insurance-florida-2026-23', destination: '/plumbing-leak-insurance-florida-2026', permanent: true },
      { source: '/plumbing-leak-insurance-florida-2026-24', destination: '/plumbing-leak-insurance-florida-2026', permanent: true },
      { source: '/plumbing-leak-insurance-florida-2026-35', destination: '/plumbing-leak-insurance-florida-2026', permanent: true },
      { source: '/port-st-lucie-water-damage-lawyer-2026-1', destination: '/port-st-lucie-water-damage-lawyer-2026', permanent: true },
      { source: '/property-damage-attorney-fort-lauderdale-2026-1', destination: '/property-damage-attorney-fort-lauderdale-2026', permanent: true },
      { source: '/property-damage-attorney-miami-2026-1', destination: '/property-damage-attorney-miami', permanent: true },
      { source: '/property-damage-attorney-pembroke-pines-2026-1', destination: '/property-damage-attorney-pembroke-pines-2026', permanent: true },
      { source: '/property-damage-attorney-tampa-2026-1', destination: '/property-damage-attorney-tampa-2026', permanent: true },
      { source: '/property-damage-lawyer-boca-raton-2026-1', destination: '/property-damage-lawyer-boca-raton', permanent: true },
      { source: '/property-damage-lawyer-jacksonville-2026-2', destination: '/property-damage-lawyer-jacksonville-2026', permanent: true },
      { source: '/property-damage-lawyer-miami-2026-1', destination: '/property-damage-lawyer-miami-2026', permanent: true },
      { source: '/property-damage-lawyer-pembroke-pines-2026-1', destination: '/property-damage-lawyer-pembroke-pines-2026', permanent: true },
      { source: '/property-damage-lawyer-tampa-2026-1', destination: '/property-damage-lawyer-tampa-2026', permanent: true },
      { source: '/property-insurance-claim-process-fort-lauderdale-2026-1', destination: '/property-insurance-claim-process-fort-lauderdale-2026', permanent: true },
      { source: '/property-insurance-claim-process-hollywood-2026-2', destination: '/property-insurance-claim-process-hollywood-2026', permanent: true },
      { source: '/property-insurance-claim-process-miami-2026-1', destination: '/property-insurance-claim-process-miami-2026', permanent: true },
      { source: '/property-insurance-claim-process-naples-2026-1', destination: '/property-insurance-claim-process-naples-2026', permanent: true },
      { source: '/property-insurance-claim-process-pembroke-pines-2026-1', destination: '/property-insurance-claim-process-pembroke-pines-2026', permanent: true },
      { source: '/property-insurance-claim-process-west-palm-beach-2026-1', destination: '/property-insurance-claim-process-west-palm-beach-2026', permanent: true },
      { source: '/property-insurance-claim-process-west-palm-beach-2026-3', destination: '/property-insurance-claim-process-west-palm-beach-2026', permanent: true },
      { source: '/property-insurance-claim-process-west-palm-beach-2026-4', destination: '/property-insurance-claim-process-west-palm-beach-2026', permanent: true },
      { source: '/public-adjuster-vs-lawyer-orlando-2026-3', destination: '/public-adjuster-vs-lawyer-orlando-2026', permanent: true },
      { source: '/roof-leak-claim-attorney-boca-raton-2026-1', destination: '/roof-leak-claim-attorney-boca-raton-2026', permanent: true },
      { source: '/roof-leak-claim-attorney-coral-springs-2026-1', destination: '/roof-leak-claim-attorney-coral-springs-2026', permanent: true },
      { source: '/roof-leak-claim-attorney-gainesville-2026-5', destination: '/roof-leak-claim-attorney-gainesville-2026', permanent: true },
      { source: '/roof-leak-claim-attorney-hialeah-2026-1', destination: '/roof-leak-claim-attorney-hialeah-2026', permanent: true },
      { source: '/roof-leak-claim-attorney-miami-2026-1', destination: '/roof-leak-claim-attorney-miami-2026', permanent: true },
      { source: '/roof-leak-claim-attorney-miami-2026-2', destination: '/roof-leak-claim-attorney-miami-2026', permanent: true },
      { source: '/roof-leak-claim-attorney-pensacola-2026-1', destination: '/roof-leak-claim-attorney-pensacola-2026', permanent: true },
      { source: '/roof-leak-claim-attorney-port-st-lucie-2026-1', destination: '/roof-leak-claim-attorney-port-st-lucie-2026', permanent: true },
      { source: '/roof-leak-claim-attorney-tampa-2026-1', destination: '/roof-leak-claim-attorney-tampa-2026', permanent: true },
      { source: '/roof-leak-claim-attorney-west-palm-beach-2026-1', destination: '/roof-leak-claim-attorney-west-palm-beach-2026', permanent: true },
      { source: '/roof-leak-claim-attorney-west-palm-beach-2026-6', destination: '/roof-leak-claim-attorney-west-palm-beach-2026', permanent: true },
      { source: '/roof-leak-insurance-claim-colorado-2026-1', destination: '/roof-leak-insurance-claim-colorado-2026', permanent: true },
      { source: '/roof-leak-insurance-claim-florida-2026-25', destination: '/roof-leak-insurance-claim-florida-2026', permanent: true },
      { source: '/roof-leak-insurance-claim-florida-2026-7', destination: '/roof-leak-insurance-claim-florida-2026', permanent: true },
      { source: '/sinkhole-damage-coral-springs-2026-1', destination: '/sinkhole-damage-coral-springs-2026', permanent: true },
      { source: '/sinkhole-damage-coral-springs-2026-2', destination: '/sinkhole-damage-coral-springs-2026', permanent: true },
      { source: '/sinkhole-damage-miami-2026-3', destination: '/sinkhole-damage-miami-2026', permanent: true },
      { source: '/sinkhole-damage-orlando-2026-1', destination: '/sinkhole-damage-orlando-2026', permanent: true },
      { source: '/sinkhole-damage-port-st-lucie-2026-1', destination: '/sinkhole-damage-port-st-lucie-2026', permanent: true },
      { source: '/st-petersburg-water-damage-insurance-lawyer-2026-3', destination: '/st-petersburg-water-damage-insurance-lawyer-2026', permanent: true },
      { source: '/storm-damage-lawyer-coral-springs-2026-1', destination: '/storm-damage-lawyer-coral-springs-2026', permanent: true },
      { source: '/storm-damage-lawyer-coral-springs-2026-3', destination: '/storm-damage-lawyer-coral-springs-2026', permanent: true },
      { source: '/storm-damage-lawyer-fort-lauderdale-2026-1', destination: '/storm-damage-lawyer-fort-lauderdale-2026', permanent: true },
      { source: '/storm-damage-lawyer-gainesville-2026-2', destination: '/storm-damage-lawyer-gainesville-2026', permanent: true },
      { source: '/storm-damage-lawyer-jacksonville-2026-2', destination: '/storm-damage-lawyer-jacksonville-2026', permanent: true },
      { source: '/storm-damage-lawyer-miami-2026-1', destination: '/storm-damage-lawyer-miami-2026', permanent: true },
      { source: '/storm-damage-lawyer-naples-2026-1', destination: '/storm-damage-lawyer-naples-2026', permanent: true },
      { source: '/storm-damage-lawyer-orlando-2026-2', destination: '/storm-damage-lawyer-orlando-2026', permanent: true },
      { source: '/storm-damage-lawyer-pembroke-pines-2026-1', destination: '/storm-damage-lawyer-pembroke-pines-2026', permanent: true },
      { source: '/storm-damage-lawyer-pensacola-2026-1', destination: '/storm-damage-lawyer-pensacola-2026', permanent: true },
      { source: '/storm-damage-lawyer-port-st-lucie-2026-1', destination: '/storm-damage-lawyer-port-st-lucie-2026', permanent: true },
      { source: '/storm-damage-lawyer-port-st-lucie-2026-2', destination: '/storm-damage-lawyer-port-st-lucie-2026', permanent: true },
      { source: '/storm-damage-lawyer-tallahassee-2026-1', destination: '/storm-damage-lawyer-tallahassee-2026', permanent: true },
      { source: '/storm-damage-lawyer-west-palm-beach-2026-1', destination: '/storm-damage-lawyer-west-palm-beach-2026', permanent: true },
      { source: '/storm-damage-lawyer-west-palm-beach-2026-2', destination: '/storm-damage-lawyer-west-palm-beach-2026', permanent: true },
      { source: '/storm-damage-lawyer-west-palm-beach-2026-4', destination: '/storm-damage-lawyer-west-palm-beach-2026', permanent: true },
      { source: '/storm-damage-lawyer-west-palm-beach-2026-5', destination: '/storm-damage-lawyer-west-palm-beach-2026', permanent: true },
      { source: '/tallahassee-hurricane-insurance-lawyer-2026-1', destination: '/tallahassee-hurricane-insurance-lawyer-2026', permanent: true },
      { source: '/tallahassee-storm-claim-lawyer-2026-1', destination: '/tallahassee-storm-claim-lawyer-2026', permanent: true },
      { source: '/tampa-hurricane-insurance-lawyer-2026-1', destination: '/tampa-hurricane-insurance-lawyer-2026', permanent: true },
      { source: '/tampa-mold-damage-attorney-2026-1', destination: '/tampa-mold-damage-attorney-2026', permanent: true },
      { source: '/toxic-mold-insurance-claim-lawyer-hollywood-2026-1', destination: '/toxic-mold-insurance-claim-lawyer-hollywood-2026', permanent: true },
      { source: '/toxic-mold-insurance-claim-lawyer-miami-2026-1', destination: '/toxic-mold-insurance-claim-lawyer-miami-2026', permanent: true },
      { source: '/toxic-mold-insurance-claim-lawyer-orlando-2026-1', destination: '/toxic-mold-insurance-claim-lawyer-orlando-2026', permanent: true },
      { source: '/toxic-mold-insurance-claim-lawyer-west-palm-beach-2026-1', destination: '/toxic-mold-insurance-claim-lawyer-west-palm-beach-2026', permanent: true },
      { source: '/toxic-mold-insurance-coverage-florida-2026-2', destination: '/toxic-mold-insurance-coverage-florida-2026', permanent: true },
      { source: '/toxic-mold-insurance-coverage-florida-2026-41', destination: '/toxic-mold-insurance-coverage-florida-2026', permanent: true },
      { source: '/toxic-mold-lawsuit-fort-lauderdale-2026-2', destination: '/toxic-mold-lawsuit-fort-lauderdale-2026', permanent: true },
      { source: '/toxic-mold-lawsuit-hollywood-2026-1', destination: '/toxic-mold-lawsuit-hollywood-2026', permanent: true },
      { source: '/toxic-mold-lawsuit-miami-2026-1', destination: '/toxic-mold-lawsuit-miami-2026', permanent: true },
      { source: '/toxic-mold-lawsuit-orlando-2026-1', destination: '/toxic-mold-lawsuit-orlando-2026', permanent: true },
      { source: '/toxic-mold-lawsuit-pembroke-pines-2026-4', destination: '/toxic-mold-lawsuit-pembroke-pines-2026', permanent: true },
      { source: '/underpaid-insurance-claim-boca-raton-2026-1', destination: '/underpaid-insurance-claim-boca-raton-2026', permanent: true },
      { source: '/underpaid-insurance-claim-coral-springs-2026-1', destination: '/underpaid-insurance-claim-coral-springs-2026', permanent: true },
      { source: '/underpaid-insurance-claim-jacksonville-2026-3', destination: '/underpaid-insurance-claim-jacksonville-2026', permanent: true },
      { source: '/underpaid-insurance-claim-miami-2026-1', destination: '/underpaid-insurance-claim-miami-2026', permanent: true },
      { source: '/underpaid-insurance-claim-naples-2026-1', destination: '/underpaid-insurance-claim-naples-2026', permanent: true },
      { source: '/underpaid-insurance-claim-tampa-2026-1', destination: '/underpaid-insurance-claim-tampa-2026', permanent: true },
      { source: '/usaa-roof-claim-denied-florida-2026-1', destination: '/usaa-roof-claim-denied-florida-2026', permanent: true },
      { source: '/water-damage-attorney-boca-raton-2026-1', destination: '/water-damage-attorney-boca-raton-2026', permanent: true },
      { source: '/water-damage-attorney-cape-coral-2026-4', destination: '/water-damage-attorney-cape-coral-2026', permanent: true },
      { source: '/water-damage-attorney-hollywood-2026-1', destination: '/water-damage-attorney-hollywood-2026', permanent: true },
      { source: '/water-damage-attorney-miami-2026-1', destination: '/water-damage-attorney-miami-2026', permanent: true },
      { source: '/water-damage-attorney-miami-2026-6', destination: '/water-damage-attorney-miami-2026', permanent: true },
      { source: '/water-damage-attorney-orlando-2026-1', destination: '/water-damage-attorney-orlando-2026', permanent: true },
      { source: '/water-damage-attorney-orlando-2026-2', destination: '/water-damage-attorney-orlando-2026', permanent: true },
      { source: '/water-damage-attorney-sarasota-2026-5', destination: '/water-damage-attorney-sarasota-2026', permanent: true },
      { source: '/water-damage-attorney-st-petersburg-2026-1', destination: '/water-damage-attorney-st-petersburg-2026', permanent: true },
      { source: '/water-damage-attorney-st-petersburg-2026-10', destination: '/water-damage-attorney-st-petersburg-2026', permanent: true },
      { source: '/water-damage-attorney-st-petersburg-2026-4', destination: '/water-damage-attorney-st-petersburg-2026', permanent: true },
      { source: '/water-damage-attorney-tallahassee-2026-1', destination: '/water-damage-attorney-tallahassee-2026', permanent: true },
      { source: '/water-damage-attorney-west-palm-beach-2026-3', destination: '/water-damage-attorney-west-palm-beach-2026', permanent: true },
      { source: '/water-damage-claim-denied-fort-lauderdale-florida-2026-1', destination: '/water-damage-claim-denied-fort-lauderdale-florida-2026', permanent: true },
      { source: '/water-damage-claim-denied-miami-florida-2026-1', destination: '/water-damage-claim-denied-miami-florida-2026', permanent: true },
      { source: '/water-damage-claim-denied-orlando-florida-2026-1', destination: '/water-damage-claim-denied-orlando-florida-2026', permanent: true },
      { source: '/west-palm-beach-hurricane-insurance-lawyer-2026-1', destination: '/west-palm-beach-hurricane-insurance-lawyer-2026', permanent: true },
      { source: '/west-palm-beach-mold-damage-lawyer-2026-1', destination: '/west-palm-beach-mold-damage-lawyer-2026', permanent: true },
      { source: '/west-palm-beach-storm-claim-lawyer-2026-1', destination: '/west-palm-beach-storm-claim-lawyer-2026', permanent: true },
      { source: '/west-palm-beach-storm-claim-lawyer-2026-4', destination: '/west-palm-beach-storm-claim-lawyer-2026', permanent: true },
      { source: '/west-palm-beach-water-damage-insurance-lawyer-2026-3', destination: '/west-palm-beach-water-damage-insurance-lawyer-2026', permanent: true },
      { source: '/west-palm-beach-water-damage-lawyer-2026-1', destination: '/west-palm-beach-water-damage-lawyer-2026', permanent: true },
      { source: '/wind-damage-insurance-attorney-cape-coral-2026-2', destination: '/wind-damage-insurance-attorney-cape-coral-2026', permanent: true },
      { source: '/wind-damage-insurance-attorney-fort-lauderdale-2026-1', destination: '/wind-damage-insurance-attorney-fort-lauderdale-2026', permanent: true },
      { source: '/wind-damage-insurance-attorney-jacksonville-2026-1', destination: '/wind-damage-insurance-attorney-jacksonville-2026', permanent: true },
      { source: '/wind-damage-insurance-attorney-jacksonville-2026-3', destination: '/wind-damage-insurance-attorney-jacksonville-2026', permanent: true },
      { source: '/wind-damage-insurance-attorney-jacksonville-2026-4', destination: '/wind-damage-insurance-attorney-jacksonville-2026', permanent: true },
      { source: '/wind-damage-insurance-attorney-miami-2026-3', destination: '/wind-damage-insurance-attorney-miami-2026', permanent: true },
      { source: '/wind-damage-insurance-attorney-miami-2026-5', destination: '/wind-damage-insurance-attorney-miami-2026', permanent: true },
      { source: '/wind-damage-insurance-attorney-naples-2026-3', destination: '/wind-damage-insurance-attorney-naples-2026', permanent: true },
      { source: '/wind-damage-insurance-attorney-orlando-2026-1', destination: '/wind-damage-insurance-attorney-orlando-2026', permanent: true },
      { source: '/wind-damage-insurance-attorney-orlando-2026-2', destination: '/wind-damage-insurance-attorney-orlando-2026', permanent: true },
      { source: '/wind-damage-insurance-attorney-orlando-2026-3', destination: '/wind-damage-insurance-attorney-orlando-2026', permanent: true },
      { source: '/wind-damage-insurance-attorney-pensacola-2026-1', destination: '/wind-damage-insurance-attorney-pensacola-2026', permanent: true },
      { source: '/wind-damage-insurance-attorney-pensacola-2026-2', destination: '/wind-damage-insurance-attorney-pensacola-2026', permanent: true },
      { source: '/wind-damage-insurance-attorney-sarasota-2026-2', destination: '/wind-damage-insurance-attorney-sarasota-2026', permanent: true },
      { source: '/wind-damage-insurance-attorney-tallahassee-2026-1', destination: '/wind-damage-insurance-attorney-tallahassee-2026', permanent: true },
      { source: '/wind-damage-insurance-attorney-tampa-2026-3', destination: '/wind-damage-insurance-attorney-tampa-2026', permanent: true },
    ];
  },

  async rewrites() {
    // Visitor-intelligence collector forwards: the browser only ever talks to
    // same-origin /collect and /vi-config; these rewrites forward them
    // server-side to the collector origin (Cloudflare tunnel). The origin is
    // HARDCODED to the production collector so nothing depends on a Vercel env
    // var — COLLECTOR_ORIGIN is only an optional local override.
    //   /collect   → collector ingest (events / server-side submit join)
    //   /vi-config → collector master on/off switch ({enabled:true|false}).
    //                The consent script + emitter fetch /vi-config on load and
    //                stay completely dark unless it returns {enabled:true},
    //                so the collector itself is the live cutover switch.
    const VI_ORIGIN = process.env.COLLECTOR_ORIGIN || 'https://collect.louislawgroup.com';
    const viCollectorRewrites = [
      {
        source: '/collect',
        destination: `${VI_ORIGIN}/collect`,
      },
      {
        source: '/vi-config',
        destination: `${VI_ORIGIN}/config`,
      },
    ];
    return {
      beforeFiles: [
        ...viCollectorRewrites,
        {
          // Static article page with custom UI — must come before catch-all route
          source: '/case-law-insurance-claim-worth-pursuing-florida-2022-reform',
          destination: '/case-law-insurance-claim-worth-pursuing-florida-2022-reform.html',
        },
        {
          // Static report pages with custom UI
          source: '/reports/florida-insurance-market-january-2026',
          destination: '/reports/florida-insurance-market-january-2026.html',
        },
        {
          source: '/reports/florida-presuit-notice-intelligence-report',
          destination: '/reports/florida-presuit-notice-intelligence-report.html',
        },
        {
          source: '/reports/fee-reform-case-outcomes-dashboard',
          destination: '/reports/fee-reform-case-outcomes-dashboard.html',
        },
      ],
      afterFiles: [
        {
          // Rewrite /sitemaps/1.xml to /api/sitemap/1
          source: '/sitemaps/:page.xml',
          destination: '/api/sitemap/:page',
        },
      ],
      fallback: [],
    };
  },

  async headers() {
    return [
      {
        // Cache all article pages: 24h CDN, serve stale while revalidating
        source: '/:slug*',
        has: [{ type: 'header', key: 'x-nextjs-data', value: undefined }],
        headers: [
          {
            key: 'Cache-Control',
            value: 'public, s-maxage=86400, stale-while-revalidate=3600',
          },
        ],
      },
      {
        // Never cache API routes
        source: '/api/:path*',
        headers: [
          {
            key: 'Cache-Control',
            value: 'no-store',
          },
        ],
      },
    ];
  },
};

export default nextConfig;
