/** @type {import('next').NextConfig} */
const nextConfig = {
  poweredByHeader: false,
  images: {
    formats: ['image/avif', 'image/webp'],
    remotePatterns: [
      { protocol: 'https', hostname: 'login.louislawgroup.com' },
    ],
  },
  async redirects() {
    return [
      // ── SEO P0 2026-06-18: FPP twin consolidation — 301 base → -N earner (the URL Google ranked) ──
      { source: '/bad-faith-insurance-attorney-west-palm-beach-2026', destination: '/bad-faith-insurance-attorney-west-palm-beach-2026-3', permanent: true },
      { source: '/boca-raton-mold-damage-lawyer-2026', destination: '/boca-raton-mold-damage-lawyer-2026-3', permanent: true },
      { source: '/flood-damage-lawyer-sarasota-2026', destination: '/flood-damage-lawyer-sarasota-2026-5', permanent: true },
      { source: '/flooding-insurance-claim-tampa-2026', destination: '/flooding-insurance-claim-tampa-2026-2', permanent: true },
      { source: '/hail-damage-insurance-jacksonville-2026', destination: '/hail-damage-insurance-jacksonville-2026-2', permanent: true },
      { source: '/hurricane-damage-attorney-naples-2026', destination: '/hurricane-damage-attorney-naples-2026-2', permanent: true },
      { source: '/hurricane-damage-attorney-west-palm-beach-2026', destination: '/hurricane-damage-attorney-west-palm-beach-2026-7', permanent: true },
      { source: '/hurricane-damage-claim-miami-2026', destination: '/hurricane-damage-claim-miami-2026-3', permanent: true },
      { source: '/hurricane-damage-claim-pensacola-2026', destination: '/hurricane-damage-claim-pensacola-2026-2', permanent: true },
      { source: '/insurance-denied-mold-claim-florida-2026', destination: '/insurance-denied-mold-claim-florida-2026-64', permanent: true },
      { source: '/insurance-denied-mold-claim-west-palm-beach-2026', destination: '/insurance-denied-mold-claim-west-palm-beach-2026-5', permanent: true },
      { source: '/miami-water-damage-lawyer-2026', destination: '/miami-water-damage-lawyer-2026-4', permanent: true },
      { source: '/mold-damage-lawyer-miami-2026', destination: '/mold-damage-lawyer-miami-2026-4', permanent: true },
      { source: '/mold-remediation-insurance-lawyer-boca-raton-2026', destination: '/mold-remediation-insurance-lawyer-boca-raton-2026-4', permanent: true },
      { source: '/pensacola-property-damage-attorney-2026', destination: '/pensacola-property-damage-attorney-2026-5', permanent: true },
      { source: '/property-damage-lawyer-boca-raton-2026', destination: '/property-damage-lawyer-boca-raton-2026-2', permanent: true },
      { source: '/property-damage-lawyer-orlando-2026', destination: '/property-damage-lawyer-orlando-2026-5', permanent: true },
      { source: '/property-damage-lawyer-pensacola-2026', destination: '/property-damage-lawyer-pensacola-2026-3', permanent: true },
      { source: '/property-damage-lawyer-west-palm-beach-2026', destination: '/property-damage-lawyer-west-palm-beach-2026-4', permanent: true },
      { source: '/property-insurance-claim-process-tampa-2026', destination: '/property-insurance-claim-process-tampa-2026-2', permanent: true },
      { source: '/public-adjuster-vs-lawyer-boca-raton-2026', destination: '/public-adjuster-vs-lawyer-boca-raton-2026-4', permanent: true },
      { source: '/roof-leak-insurance-claim-florida-2026', destination: '/roof-leak-insurance-claim-florida-2026-34', permanent: true },
      { source: '/sarasota-hurricane-insurance-lawyer-2026', destination: '/sarasota-hurricane-insurance-lawyer-2026-2', permanent: true },
      { source: '/sarasota-property-damage-attorney-2026', destination: '/sarasota-property-damage-attorney-2026-3', permanent: true },
      { source: '/st-petersburg-water-damage-lawyer-2026', destination: '/st-petersburg-water-damage-lawyer-2026-2', permanent: true },
      { source: '/storm-damage-insurance-claim-florida-2026', destination: '/storm-damage-insurance-claim-florida-2026-7', permanent: true },
      { source: '/toxic-mold-insurance-claim-lawyer-orlando-2026', destination: '/toxic-mold-insurance-claim-lawyer-orlando-2026-8', permanent: true },
      { source: '/toxic-mold-lawsuit-boca-raton-2026', destination: '/toxic-mold-lawsuit-boca-raton-2026-7', permanent: true },
      { source: '/toxic-mold-lawsuit-gainesville-2026', destination: '/toxic-mold-lawsuit-gainesville-2026-3', permanent: true },
      { source: '/toxic-mold-lawsuit-jacksonville-2026', destination: '/toxic-mold-lawsuit-jacksonville-2026-4', permanent: true },
      { source: '/underpaid-insurance-claim-boca-raton-2026', destination: '/underpaid-insurance-claim-boca-raton-2026-2', permanent: true },
      { source: '/water-damage-attorney-miami-2026', destination: '/water-damage-attorney-miami-2026-5', permanent: true },
      { source: '/wind-damage-insurance-attorney-coral-springs-2026', destination: '/wind-damage-insurance-attorney-coral-springs-2026-4', permanent: true },
      { source: '/wind-damage-insurance-attorney-miami-2026', destination: '/wind-damage-insurance-attorney-miami-2026-7', permanent: true },
      // Removed former team members — bio pages redirect to /team
      { source: '/romina-murias', destination: '/team', permanent: true },
      { source: '/team/romina-murias', destination: '/team', permanent: true },
      { source: '/kellei-johnson', destination: '/team', permanent: true },
      { source: '/team/kellei-johnson', destination: '/team', permanent: true },
      { source: '/monica-abay', destination: '/team', permanent: true },
      { source: '/team/monica-abay', destination: '/team', permanent: true },

      // ── AHS consolidation (2,568 thin city pages → 1 hub) ──
      // Redirects all AHS article variants to the privacy torts landing page.
      // The privacy torts page (/american-home-shield-privacy-torts) is a static
      // route so it won't be caught by these patterns.

      // ahs-* (61+ pages: ahs-claim-denial-*, ahs-guide-*, ahs-coverage-*, etc.)
      { source: '/ahs-:slug*', destination: '/american-home-shield-privacy-torts', permanent: true },

      // american-home-shield-claim-* (807 pages)
      { source: '/american-home-shield-claim-:slug*', destination: '/american-home-shield-privacy-torts', permanent: true },

      // american-home-shield-guide-* and guide-to-american-* and guide-american-home-* (2,302 pages)
      { source: '/american-home-shield-guide-:slug*', destination: '/american-home-shield-privacy-torts', permanent: true },
      { source: '/guide-to-american-:slug*', destination: '/american-home-shield-privacy-torts', permanent: true },
      { source: '/guide-american-home-:slug*', destination: '/american-home-shield-privacy-torts', permanent: true },

      // american-home-shield-denied-* (denied claims)
      { source: '/american-home-shield-denied-:slug*', destination: '/american-home-shield-privacy-torts', permanent: true },

      // american-home-shield-rights-* and your-rights-after-american-*
      { source: '/american-home-shield-rights-:slug*', destination: '/american-home-shield-privacy-torts', permanent: true },
      { source: '/your-rights-:slug(.*american-home-shield.*)', destination: '/american-home-shield-privacy-torts', permanent: true },
      { source: '/your-guide-to-:slug(.*american-home-shield.*)', destination: '/american-home-shield-privacy-torts', permanent: true },

      // american-home-shield-lawsuit-*, american-home-shield-sue-*
      { source: '/american-home-shield-lawsuit-:slug*', destination: '/american-home-shield-privacy-torts', permanent: true },
      { source: '/american-home-shield-sue-:slug*', destination: '/american-home-shield-privacy-torts', permanent: true },
      { source: '/sue-american-home-:slug*', destination: '/american-home-shield-privacy-torts', permanent: true },

      // american-home-shield-coverage-*
      { source: '/american-home-shield-coverage-:slug*', destination: '/american-home-shield-privacy-torts', permanent: true },

      // legal-guide-american-*, legal-american-home-*
      { source: '/legal-guide-american-:slug*', destination: '/american-home-shield-privacy-torts', permanent: true },
      { source: '/legal-american-home-:slug*', destination: '/american-home-shield-privacy-torts', permanent: true },

      // ── Allstate cannibalization fix (2026-04-01) ──
      // Texas variant competes with main Allstate page — LLG doesn't practice in TX.
      // Consolidate 1,162 impr into the main page at pos 3.9
      { source: '/allstate-denied-my-roof-claim-texas', destination: '/allstate-denied-my-roof-claim', permanent: true },

      // ── Personal Injury section (2026-04-13) ──
      // Nav link in Strapi points to /personal-injury-attorneys → redirect to new static PI page
      { source: '/personal-injury-attorneys', destination: '/personal-injury', permanent: true },


      // ── FPP suffix-duplicate 301s (284 pages, 2026-04-18) ──
      { source: '/allstate-claim-denial-attorney-2026-1', destination: '/allstate-claim-denial-attorney-2026', permanent: true },
      { source: '/allstate-insurance-denied-claim-florida-2026-1', destination: '/allstate-insurance-denied-claim-florida-2026', permanent: true },
      { source: '/allstate-roof-claim-denied-texas-2026-1', destination: '/allstate-roof-claim-denied-texas-2026', permanent: true },
      { source: '/bad-faith-insurance-attorney-orlando-2026-1', destination: '/bad-faith-insurance-attorney-orlando-2026', permanent: true },
      { source: '/bad-faith-insurance-attorney-st-petersburg-2026-1', destination: '/bad-faith-insurance-attorney-st-petersburg-2026', permanent: true },
      { source: '/bad-faith-insurance-attorney-st-petersburg-2026-2', destination: '/bad-faith-insurance-attorney-st-petersburg-2026', permanent: true },
      { source: '/bad-faith-insurance-attorney-tampa-2026-1', destination: '/bad-faith-insurance-attorney-tampa-2026', permanent: true },
      { source: '/black-mold-insurance-claim-hollywood-2026-1', destination: '/black-mold-insurance-claim-hollywood-2026', permanent: true },
      { source: '/boca-raton-fire-damage-attorney-2026-1', destination: '/boca-raton-fire-damage-attorney-2026', permanent: true },
      { source: '/boca-raton-hurricane-insurance-lawyer-2026-2', destination: '/boca-raton-hurricane-insurance-lawyer-2026', permanent: true },
      { source: '/boca-raton-water-damage-insurance-lawyer-2026-3', destination: '/boca-raton-water-damage-insurance-lawyer-2026', permanent: true },
      { source: '/boca-raton-water-damage-lawyer-2026-1', destination: '/boca-raton-water-damage-lawyer-2026', permanent: true },
      { source: '/burst-pipe-insurance-claim-coral-springs-2026-1', destination: '/burst-pipe-insurance-claim-coral-springs-2026', permanent: true },
      { source: '/burst-pipe-insurance-claim-fort-lauderdale-2026-1', destination: '/burst-pipe-insurance-claim-fort-lauderdale-2026', permanent: true },
      { source: '/coral-springs-hurricane-insurance-lawyer-2026-1', destination: '/coral-springs-hurricane-insurance-lawyer-2026', permanent: true },
      { source: '/coral-springs-hurricane-insurance-lawyer-2026-2', destination: '/coral-springs-hurricane-insurance-lawyer-2026', permanent: true },
      { source: '/coral-springs-storm-claim-lawyer-2026-1', destination: '/coral-springs-storm-claim-lawyer-2026', permanent: true },
      { source: '/denied-insurance-claim-lawyer-coral-springs-2026-1', destination: '/denied-insurance-claim-lawyer-coral-springs-2026', permanent: true },
      { source: '/denied-insurance-claim-lawyer-jacksonville-2026-1', destination: '/denied-insurance-claim-lawyer-jacksonville-2026', permanent: true },
      { source: '/denied-insurance-claim-lawyer-miami-2026-3', destination: '/denied-insurance-claim-lawyer-miami-2026', permanent: true },
      { source: '/denied-insurance-claim-lawyer-naples-2026-1', destination: '/denied-insurance-claim-lawyer-naples-2026', permanent: true },
      { source: '/denied-insurance-claim-lawyer-pembroke-pines-2026-1', destination: '/denied-insurance-claim-lawyer-pembroke-pines-2026', permanent: true },
      { source: '/denied-insurance-claim-lawyer-st-petersburg-2026-1', destination: '/denied-insurance-claim-lawyer-st-petersburg-2026', permanent: true },
      { source: '/denied-insurance-claim-lawyer-st-petersburg-2026-4', destination: '/denied-insurance-claim-lawyer-st-petersburg-2026', permanent: true },
      { source: '/denied-insurance-claim-lawyer-tampa-2026-1', destination: '/denied-insurance-claim-lawyer-tampa-2026', permanent: true },
      { source: '/documenting-property-damage-florida-2026-1', destination: '/documenting-property-damage-florida-2026', permanent: true },
      { source: '/documenting-property-damage-florida-2026-4', destination: '/documenting-property-damage-florida-2026', permanent: true },
      { source: '/fight-kin-insurance-denial-florida-2026-1', destination: '/fight-kin-insurance-denial-florida-2026', permanent: true },
      { source: '/fire-damage-claim-coral-springs-2026-1', destination: '/fire-damage-claim-coral-springs-2026', permanent: true },
      { source: '/fire-damage-claim-gainesville-2026-1', destination: '/fire-damage-claim-gainesville-2026', permanent: true },
      { source: '/fire-damage-claim-hollywood-2026-1', destination: '/fire-damage-claim-hollywood-2026', permanent: true },
      { source: '/fire-damage-claim-miami-2026-1', destination: '/fire-damage-claim-miami-2026', permanent: true },
      { source: '/fire-damage-claim-naples-2026-1', destination: '/fire-damage-claim-naples-2026', permanent: true },
      { source: '/fire-damage-claim-orlando-2026-1', destination: '/fire-damage-claim-orlando-2026', permanent: true },
      { source: '/flood-damage-lawyer-coral-springs-2026-2', destination: '/flood-damage-lawyer-coral-springs-2026', permanent: true },
      { source: '/flood-damage-lawyer-fort-lauderdale-2026-1', destination: '/flood-damage-lawyer-fort-lauderdale-2026', permanent: true },
      { source: '/flood-damage-lawyer-fort-lauderdale-2026-2', destination: '/flood-damage-lawyer-fort-lauderdale-2026', permanent: true },
      { source: '/flood-damage-lawyer-hialeah-2026-1', destination: '/flood-damage-lawyer-hialeah-2026', permanent: true },
      { source: '/flood-damage-lawyer-hollywood-2026-1', destination: '/flood-damage-lawyer-hollywood-2026', permanent: true },
      { source: '/flood-damage-lawyer-hollywood-2026-2', destination: '/flood-damage-lawyer-hollywood-2026', permanent: true },
      { source: '/flood-damage-lawyer-jacksonville-2026-2', destination: '/flood-damage-lawyer-jacksonville-2026', permanent: true },
      { source: '/flood-damage-lawyer-jacksonville-2026-3', destination: '/flood-damage-lawyer-jacksonville-2026', permanent: true },
      { source: '/flood-damage-lawyer-miami-2026-1', destination: '/flood-damage-lawyer-miami-2026', permanent: true },
      { source: '/flood-damage-lawyer-orlando-2026-1', destination: '/flood-damage-lawyer-orlando-2026', permanent: true },
      { source: '/flood-damage-lawyer-orlando-2026-7', destination: '/flood-damage-lawyer-orlando-2026', permanent: true },
      { source: '/flood-damage-lawyer-pembroke-pines-2026-2', destination: '/flood-damage-lawyer-pembroke-pines-2026', permanent: true },
      { source: '/flood-damage-lawyer-port-st-lucie-2026-1', destination: '/flood-damage-lawyer-port-st-lucie-2026', permanent: true },
      { source: '/flood-damage-lawyer-port-st-lucie-2026-2', destination: '/flood-damage-lawyer-port-st-lucie-2026', permanent: true },
      { source: '/flood-damage-lawyer-port-st-lucie-2026-5', destination: '/flood-damage-lawyer-port-st-lucie-2026', permanent: true },
      { source: '/flood-damage-lawyer-sarasota-2026-1', destination: '/flood-damage-lawyer-sarasota-2026', permanent: true },
      { source: '/flood-damage-lawyer-sarasota-2026-4', destination: '/flood-damage-lawyer-sarasota-2026', permanent: true },
      { source: '/flood-damage-lawyer-tampa-2026-1', destination: '/flood-damage-lawyer-tampa-2026', permanent: true },
      { source: '/flooding-insurance-claim-boca-raton-2026-1', destination: '/flooding-insurance-claim-boca-raton-2026', permanent: true },
      { source: '/flooding-insurance-claim-boca-raton-2026-2', destination: '/flooding-insurance-claim-boca-raton-2026', permanent: true },
      { source: '/flooding-insurance-claim-coral-springs-2026-1', destination: '/flooding-insurance-claim-coral-springs-2026', permanent: true },
      { source: '/flooding-insurance-claim-fort-lauderdale-2026-1', destination: '/flooding-insurance-claim-fort-lauderdale-2026', permanent: true },
      { source: '/flooding-insurance-claim-miami-2026-4', destination: '/flooding-insurance-claim-miami-2026', permanent: true },
      { source: '/flooding-insurance-claim-naples-2026-1', destination: '/flooding-insurance-claim-naples-2026', permanent: true },
      { source: '/flooding-insurance-claim-orlando-2026-1', destination: '/flooding-insurance-claim-orlando-2026', permanent: true },
      { source: '/fort-lauderdale-hurricane-insurance-lawyer-2026-1', destination: '/fort-lauderdale-hurricane-insurance-lawyer-2026', permanent: true },
      { source: '/fort-lauderdale-property-damage-attorney-2026-5', destination: '/fort-lauderdale-property-damage-attorney-2026', permanent: true },
      { source: '/fort-lauderdale-property-damage-attorney-2026-9', destination: '/fort-lauderdale-property-damage-attorney-2026', permanent: true },
      { source: '/fort-lauderdale-storm-claim-lawyer-2026-1', destination: '/fort-lauderdale-storm-claim-lawyer-2026', permanent: true },
      { source: '/fort-lauderdale-water-damage-insurance-lawyer-2026-3', destination: '/fort-lauderdale-water-damage-insurance-lawyer-2026', permanent: true },
      { source: '/fort-lauderdale-water-damage-insurance-lawyer-2026-4', destination: '/fort-lauderdale-water-damage-insurance-lawyer-2026', permanent: true },
      { source: '/fort-lauderdale-water-damage-lawyer-2026-1', destination: '/fort-lauderdale-water-damage-lawyer-2026', permanent: true },
      { source: '/gainesville-hurricane-insurance-lawyer-2026-1', destination: '/gainesville-hurricane-insurance-lawyer-2026', permanent: true },
      { source: '/hail-damage-insurance-boca-raton-2026-1', destination: '/hail-damage-insurance-boca-raton-2026', permanent: true },
      { source: '/hail-damage-insurance-port-st-lucie-2026-1', destination: '/hail-damage-insurance-port-st-lucie-2026', permanent: true },
      { source: '/hail-damage-insurance-tampa-2026-6', destination: '/hail-damage-insurance-tampa-2026', permanent: true },
      { source: '/hail-damage-insurance-west-palm-beach-2026-1', destination: '/hail-damage-insurance-west-palm-beach-2026', permanent: true },
      { source: '/hail-damage-insurance-west-palm-beach-2026-3', destination: '/hail-damage-insurance-west-palm-beach-2026', permanent: true },
      { source: '/hialeah-hurricane-insurance-lawyer-2026-1', destination: '/hialeah-hurricane-insurance-lawyer-2026', permanent: true },
      { source: '/hialeah-storm-claim-lawyer-2026-7', destination: '/hialeah-storm-claim-lawyer-2026', permanent: true },
      { source: '/hollywood-fire-damage-attorney-2026-1', destination: '/hollywood-fire-damage-attorney-2026', permanent: true },
      { source: '/hollywood-hurricane-insurance-lawyer-2026-1', destination: '/hollywood-hurricane-insurance-lawyer-2026', permanent: true },
      { source: '/hollywood-mold-damage-lawyer-2026-1', destination: '/hollywood-mold-damage-lawyer-2026', permanent: true },
      { source: '/hollywood-property-damage-attorney-2026-1', destination: '/hollywood-property-damage-attorney-2026', permanent: true },
      { source: '/house-fire-insurance-claim-denied-florida-2026-46', destination: '/house-fire-insurance-claim-denied-florida-2026', permanent: true },
      { source: '/how-to-file-property-damage-claim-florida-2026-11', destination: '/how-to-file-property-damage-claim-florida-2026', permanent: true },
      { source: '/how-to-file-property-damage-claim-florida-2026-14', destination: '/how-to-file-property-damage-claim-florida-2026', permanent: true },
      { source: '/hurricane-damage-attorney-coral-springs-2026-1', destination: '/hurricane-damage-attorney-coral-springs-2026', permanent: true },
      { source: '/hurricane-damage-attorney-gainesville-2026-5', destination: '/hurricane-damage-attorney-gainesville-2026', permanent: true },
      { source: '/hurricane-damage-attorney-miami-2026-1', destination: '/hurricane-damage-attorney-miami-2026', permanent: true },
      { source: '/hurricane-damage-attorney-naples-2026-1', destination: '/hurricane-damage-attorney-naples-2026', permanent: true },
      { source: '/hurricane-damage-attorney-orlando-2026-1', destination: '/hurricane-damage-attorney-orlando-2026', permanent: true },
      { source: '/hurricane-damage-attorney-pembroke-pines-2026-2', destination: '/hurricane-damage-attorney-pembroke-pines-2026', permanent: true },
      { source: '/hurricane-damage-attorney-pembroke-pines-2026-4', destination: '/hurricane-damage-attorney-pembroke-pines-2026', permanent: true },
      { source: '/hurricane-damage-attorney-pensacola-2026-2', destination: '/hurricane-damage-attorney-pensacola-2026', permanent: true },
      { source: '/hurricane-damage-attorney-pensacola-2026-3', destination: '/hurricane-damage-attorney-pensacola-2026', permanent: true },
      { source: '/hurricane-damage-attorney-sarasota-2026-1', destination: '/hurricane-damage-attorney-sarasota-2026', permanent: true },
      { source: '/hurricane-damage-claim-fort-lauderdale-2026-2', destination: '/hurricane-damage-claim-fort-lauderdale-2026', permanent: true },
      { source: '/hurricane-damage-claim-gainesville-2026-2', destination: '/hurricane-damage-claim-gainesville-2026', permanent: true },
      { source: '/hurricane-damage-claim-hialeah-2026-1', destination: '/hurricane-damage-claim-hialeah-2026', permanent: true },
      { source: '/hurricane-damage-claim-miami-2026-1', destination: '/hurricane-damage-claim-miami-2026', permanent: true },
      { source: '/hurricane-damage-claim-port-st-lucie-2026-1', destination: '/hurricane-damage-claim-port-st-lucie-2026', permanent: true },
      { source: '/hurricane-damage-claim-west-palm-beach-2026-1', destination: '/hurricane-damage-claim-west-palm-beach-2026', permanent: true },
      { source: '/insurance-bad-faith-jacksonville-florida-2026-1', destination: '/insurance-bad-faith-jacksonville-florida-2026', permanent: true },
      { source: '/insurance-bad-faith-st-petersburg-florida-2026-1', destination: '/insurance-bad-faith-st-petersburg-florida-2026', permanent: true },
      { source: '/insurance-claim-attorney-coral-springs-2026-1', destination: '/insurance-claim-attorney-coral-springs-2026', permanent: true },
      { source: '/insurance-claim-attorney-hollywood-2026-1', destination: '/insurance-claim-attorney-hollywood-2026', permanent: true },
      { source: '/insurance-claim-attorney-jacksonville-2026-1', destination: '/insurance-claim-attorney-jacksonville-2026', permanent: true },
      { source: '/insurance-claim-attorney-miami-2026-1', destination: '/insurance-claim-attorney-miami-2026', permanent: true },
      { source: '/insurance-claim-attorney-naples-2026-1', destination: '/insurance-claim-attorney-naples-2026', permanent: true },
      { source: '/insurance-claim-attorney-orlando-2026-1', destination: '/insurance-claim-attorney-orlando-2026', permanent: true },
      { source: '/insurance-claim-attorney-orlando-2026-2', destination: '/insurance-claim-attorney-orlando-2026', permanent: true },
      { source: '/insurance-claim-attorney-tampa-2026-1', destination: '/insurance-claim-attorney-tampa-2026', permanent: true },
      { source: '/insurance-claim-attorney-west-palm-beach-2026-1', destination: '/insurance-claim-attorney-west-palm-beach-2026', permanent: true },
      { source: '/insurance-company-delay-tactics-florida-2026-27', destination: '/insurance-company-delay-tactics-florida-2026', permanent: true },
      { source: '/insurance-denied-mold-claim-florida-2026-1', destination: '/insurance-denied-mold-claim-florida-2026', permanent: true },
      { source: '/insurance-denied-mold-claim-florida-2026-21', destination: '/insurance-denied-mold-claim-florida-2026', permanent: true },
      { source: '/insurance-denied-mold-claim-florida-2026-32', destination: '/insurance-denied-mold-claim-florida-2026', permanent: true },
      { source: '/insurance-denied-mold-claim-florida-2026-9', destination: '/insurance-denied-mold-claim-florida-2026', permanent: true },
      { source: '/insurance-denied-mold-claim-naples-2026-1', destination: '/insurance-denied-mold-claim-naples-2026', permanent: true },
      { source: '/insurance-denied-mold-claim-orlando-2026-3', destination: '/insurance-denied-mold-claim-orlando-2026', permanent: true },
      { source: '/insurance-denied-mold-claim-pembroke-pines-2026-1', destination: '/insurance-denied-mold-claim-pembroke-pines-2026', permanent: true },
      { source: '/insurance-denied-mold-claim-pembroke-pines-2026-2', destination: '/insurance-denied-mold-claim-pembroke-pines-2026', permanent: true },
      { source: '/insurance-denied-mold-claim-west-palm-beach-2026-4', destination: '/insurance-denied-mold-claim-west-palm-beach-2026', permanent: true },
      { source: '/insurance-denied-mold-claim-west-palm-beach-2026-6', destination: '/insurance-denied-mold-claim-west-palm-beach-2026', permanent: true },
      { source: '/insurance-denied-water-damage-claim-florida-2026-18', destination: '/insurance-denied-water-damage-claim-florida-2026', permanent: true },
      { source: '/insurance-denied-water-damage-claim-florida-2026-3', destination: '/insurance-denied-water-damage-claim-florida-2026', permanent: true },
      { source: '/insurance-denied-water-damage-claim-florida-2026-30', destination: '/insurance-denied-water-damage-claim-florida-2026', permanent: true },
      { source: '/insurance-denied-water-damage-claim-florida-2026-31', destination: '/insurance-denied-water-damage-claim-florida-2026', permanent: true },
      { source: '/insurance-denied-water-damage-claim-florida-2026-35', destination: '/insurance-denied-water-damage-claim-florida-2026', permanent: true },
      { source: '/jacksonville-storm-claim-lawyer-2026-1', destination: '/jacksonville-storm-claim-lawyer-2026', permanent: true },
      { source: '/jacksonville-storm-claim-lawyer-2026-7', destination: '/jacksonville-storm-claim-lawyer-2026', permanent: true },
      { source: '/jacksonville-water-damage-lawyer-2026-1', destination: '/jacksonville-water-damage-lawyer-2026', permanent: true },
      { source: '/miami-fire-damage-attorney-2026-1', destination: '/miami-fire-damage-attorney-2026', permanent: true },
      { source: '/miami-mold-damage-attorney-2026-2', destination: '/miami-mold-damage-attorney-2026', permanent: true },
      { source: '/miami-mold-damage-lawyer-2026-1', destination: '/miami-mold-damage-lawyer-2026', permanent: true },
      { source: '/miami-property-damage-attorney-2026-1', destination: '/miami-property-damage-attorney-2026', permanent: true },
      { source: '/miami-storm-claim-lawyer-2026-5', destination: '/miami-storm-claim-lawyer-2026', permanent: true },
      { source: '/miami-water-damage-lawyer-2026-1', destination: '/miami-water-damage-lawyer-2026', permanent: true },
      { source: '/mold-coverage-dispute-hollywood-2026-1', destination: '/mold-coverage-dispute-hollywood-2026', permanent: true },
      { source: '/mold-coverage-dispute-hollywood-2026-3', destination: '/mold-coverage-dispute-hollywood-2026', permanent: true },
      { source: '/mold-coverage-dispute-orlando-2026-1', destination: '/mold-coverage-dispute-orlando-2026', permanent: true },
      { source: '/mold-coverage-dispute-pembroke-pines-2026-1', destination: '/mold-coverage-dispute-pembroke-pines-2026', permanent: true },
      { source: '/mold-damage-attorney-hollywood-2026-1', destination: '/mold-damage-attorney-hollywood-2026', permanent: true },
      { source: '/mold-damage-attorney-miami-2026-1', destination: '/mold-damage-attorney-miami-2026', permanent: true },
      { source: '/mold-damage-insurance-claim-hollywood-2026-2', destination: '/mold-damage-insurance-claim-hollywood-2026', permanent: true },
      { source: '/mold-damage-insurance-claim-hollywood-2026-3', destination: '/mold-damage-insurance-claim-hollywood-2026', permanent: true },
      { source: '/mold-damage-insurance-claim-pembroke-pines-2026-2', destination: '/mold-damage-insurance-claim-pembroke-pines-2026', permanent: true },
      { source: '/mold-damage-lawyer-boca-raton-2026-7', destination: '/mold-damage-lawyer-boca-raton-2026', permanent: true },
      { source: '/mold-damage-lawyer-miami-2026-1', destination: '/mold-damage-lawyer-miami-2026', permanent: true },
      { source: '/mold-damage-lawyer-orlando-2026-1', destination: '/mold-damage-lawyer-orlando-2026', permanent: true },
      { source: '/mold-damage-lawyer-pensacola-2026-4', destination: '/mold-damage-lawyer-pensacola-2026', permanent: true },
      { source: '/mold-insurance-claim-denied-naples-2026-3', destination: '/mold-insurance-claim-denied-naples-2026', permanent: true },
      { source: '/mold-insurance-claim-denied-naples-2026-4', destination: '/mold-insurance-claim-denied-naples-2026', permanent: true },
      { source: '/mold-insurance-claim-denied-port-st-lucie-2026-3', destination: '/mold-insurance-claim-denied-port-st-lucie-2026', permanent: true },
      { source: '/mold-remediation-insurance-lawyer-boca-raton-2026-1', destination: '/mold-remediation-insurance-lawyer-boca-raton-2026', permanent: true },
      { source: '/mold-remediation-insurance-lawyer-hollywood-2026-1', destination: '/mold-remediation-insurance-lawyer-hollywood-2026', permanent: true },
      { source: '/mold-remediation-insurance-lawyer-orlando-2026-1', destination: '/mold-remediation-insurance-lawyer-orlando-2026', permanent: true },
      { source: '/mold-remediation-insurance-lawyer-pembroke-pines-2026-1', destination: '/mold-remediation-insurance-lawyer-pembroke-pines-2026', permanent: true },
      { source: '/orlando-fire-damage-attorney-2026-1', destination: '/orlando-fire-damage-attorney-2026', permanent: true },
      { source: '/orlando-hurricane-insurance-lawyer-2026-1', destination: '/orlando-hurricane-insurance-lawyer-2026', permanent: true },
      { source: '/orlando-hurricane-insurance-lawyer-2026-4', destination: '/orlando-hurricane-insurance-lawyer-2026', permanent: true },
      { source: '/orlando-mold-damage-lawyer-2026-3', destination: '/orlando-mold-damage-lawyer-2026', permanent: true },
      { source: '/orlando-water-damage-lawyer-2026-1', destination: '/orlando-water-damage-lawyer-2026', permanent: true },
      { source: '/pembroke-pines-hurricane-insurance-lawyer-2026-1', destination: '/pembroke-pines-hurricane-insurance-lawyer-2026', permanent: true },
      { source: '/pembroke-pines-storm-claim-lawyer-2026-5', destination: '/pembroke-pines-storm-claim-lawyer-2026', permanent: true },
      { source: '/pembroke-pines-water-damage-insurance-lawyer-2026-5', destination: '/pembroke-pines-water-damage-insurance-lawyer-2026', permanent: true },
      { source: '/pensacola-property-damage-attorney-2026-1', destination: '/pensacola-property-damage-attorney-2026', permanent: true },
      { source: '/pensacola-property-damage-attorney-2026-2', destination: '/pensacola-property-damage-attorney-2026', permanent: true },
      { source: '/pensacola-water-damage-lawyer-2026-3', destination: '/pensacola-water-damage-lawyer-2026', permanent: true },
      { source: '/plumbing-leak-insurance-florida-2026-15', destination: '/plumbing-leak-insurance-florida-2026', permanent: true },
      { source: '/plumbing-leak-insurance-florida-2026-23', destination: '/plumbing-leak-insurance-florida-2026', permanent: true },
      { source: '/plumbing-leak-insurance-florida-2026-24', destination: '/plumbing-leak-insurance-florida-2026', permanent: true },
      { source: '/plumbing-leak-insurance-florida-2026-35', destination: '/plumbing-leak-insurance-florida-2026', permanent: true },
      { source: '/port-st-lucie-water-damage-lawyer-2026-1', destination: '/port-st-lucie-water-damage-lawyer-2026', permanent: true },
      { source: '/property-damage-attorney-fort-lauderdale-2026-1', destination: '/property-damage-attorney-fort-lauderdale-2026', permanent: true },
      { source: '/property-damage-attorney-miami-2026-1', destination: '/property-damage-attorney-miami', permanent: true },
      { source: '/property-damage-attorney-pembroke-pines-2026-1', destination: '/property-damage-attorney-pembroke-pines-2026', permanent: true },
      { source: '/property-damage-attorney-tampa-2026-1', destination: '/property-damage-attorney-tampa-2026', permanent: true },
      { source: '/property-damage-lawyer-boca-raton-2026-1', destination: '/property-damage-lawyer-boca-raton', permanent: true },
      { source: '/property-damage-lawyer-jacksonville-2026-2', destination: '/property-damage-lawyer-jacksonville-2026', permanent: true },
      { source: '/property-damage-lawyer-miami-2026-1', destination: '/property-damage-lawyer-miami-2026', permanent: true },
      { source: '/property-damage-lawyer-pembroke-pines-2026-1', destination: '/property-damage-lawyer-pembroke-pines-2026', permanent: true },
      { source: '/property-damage-lawyer-tampa-2026-1', destination: '/property-damage-lawyer-tampa-2026', permanent: true },
      { source: '/property-insurance-claim-process-fort-lauderdale-2026-1', destination: '/property-insurance-claim-process-fort-lauderdale-2026', permanent: true },
      { source: '/property-insurance-claim-process-hollywood-2026-2', destination: '/property-insurance-claim-process-hollywood-2026', permanent: true },
      { source: '/property-insurance-claim-process-miami-2026-1', destination: '/property-insurance-claim-process-miami-2026', permanent: true },
      { source: '/property-insurance-claim-process-naples-2026-1', destination: '/property-insurance-claim-process-naples-2026', permanent: true },
      { source: '/property-insurance-claim-process-pembroke-pines-2026-1', destination: '/property-insurance-claim-process-pembroke-pines-2026', permanent: true },
      { source: '/property-insurance-claim-process-west-palm-beach-2026-1', destination: '/property-insurance-claim-process-west-palm-beach-2026', permanent: true },
      { source: '/property-insurance-claim-process-west-palm-beach-2026-3', destination: '/property-insurance-claim-process-west-palm-beach-2026', permanent: true },
      { source: '/property-insurance-claim-process-west-palm-beach-2026-4', destination: '/property-insurance-claim-process-west-palm-beach-2026', permanent: true },
      { source: '/public-adjuster-vs-lawyer-orlando-2026-3', destination: '/public-adjuster-vs-lawyer-orlando-2026', permanent: true },
      { source: '/roof-leak-claim-attorney-boca-raton-2026-1', destination: '/roof-leak-claim-attorney-boca-raton-2026', permanent: true },
      { source: '/roof-leak-claim-attorney-coral-springs-2026-1', destination: '/roof-leak-claim-attorney-coral-springs-2026', permanent: true },
      { source: '/roof-leak-claim-attorney-gainesville-2026-5', destination: '/roof-leak-claim-attorney-gainesville-2026', permanent: true },
      { source: '/roof-leak-claim-attorney-hialeah-2026-1', destination: '/roof-leak-claim-attorney-hialeah-2026', permanent: true },
      { source: '/roof-leak-claim-attorney-miami-2026-1', destination: '/roof-leak-claim-attorney-miami-2026', permanent: true },
      { source: '/roof-leak-claim-attorney-miami-2026-2', destination: '/roof-leak-claim-attorney-miami-2026', permanent: true },
      { source: '/roof-leak-claim-attorney-pensacola-2026-1', destination: '/roof-leak-claim-attorney-pensacola-2026', permanent: true },
      { source: '/roof-leak-claim-attorney-port-st-lucie-2026-1', destination: '/roof-leak-claim-attorney-port-st-lucie-2026', permanent: true },
      { source: '/roof-leak-claim-attorney-tampa-2026-1', destination: '/roof-leak-claim-attorney-tampa-2026', permanent: true },
      { source: '/roof-leak-claim-attorney-west-palm-beach-2026-1', destination: '/roof-leak-claim-attorney-west-palm-beach-2026', permanent: true },
      { source: '/roof-leak-claim-attorney-west-palm-beach-2026-6', destination: '/roof-leak-claim-attorney-west-palm-beach-2026', permanent: true },
      { source: '/roof-leak-insurance-claim-colorado-2026-1', destination: '/roof-leak-insurance-claim-colorado-2026', permanent: true },
      { source: '/roof-leak-insurance-claim-florida-2026-25', destination: '/roof-leak-insurance-claim-florida-2026', permanent: true },
      { source: '/roof-leak-insurance-claim-florida-2026-7', destination: '/roof-leak-insurance-claim-florida-2026', permanent: true },
      { source: '/sinkhole-damage-coral-springs-2026-1', destination: '/sinkhole-damage-coral-springs-2026', permanent: true },
      { source: '/sinkhole-damage-coral-springs-2026-2', destination: '/sinkhole-damage-coral-springs-2026', permanent: true },
      { source: '/sinkhole-damage-miami-2026-3', destination: '/sinkhole-damage-miami-2026', permanent: true },
      { source: '/sinkhole-damage-orlando-2026-1', destination: '/sinkhole-damage-orlando-2026', permanent: true },
      { source: '/sinkhole-damage-port-st-lucie-2026-1', destination: '/sinkhole-damage-port-st-lucie-2026', permanent: true },
      { source: '/st-petersburg-water-damage-insurance-lawyer-2026-3', destination: '/st-petersburg-water-damage-insurance-lawyer-2026', permanent: true },
      { source: '/storm-damage-lawyer-coral-springs-2026-1', destination: '/storm-damage-lawyer-coral-springs-2026', permanent: true },
      { source: '/storm-damage-lawyer-coral-springs-2026-3', destination: '/storm-damage-lawyer-coral-springs-2026', permanent: true },
      { source: '/storm-damage-lawyer-fort-lauderdale-2026-1', destination: '/storm-damage-lawyer-fort-lauderdale-2026', permanent: true },
      { source: '/storm-damage-lawyer-gainesville-2026-2', destination: '/storm-damage-lawyer-gainesville-2026', permanent: true },
      { source: '/storm-damage-lawyer-jacksonville-2026-2', destination: '/storm-damage-lawyer-jacksonville-2026', permanent: true },
      { source: '/storm-damage-lawyer-miami-2026-1', destination: '/storm-damage-lawyer-miami-2026', permanent: true },
      { source: '/storm-damage-lawyer-naples-2026-1', destination: '/storm-damage-lawyer-naples-2026', permanent: true },
      { source: '/storm-damage-lawyer-orlando-2026-2', destination: '/storm-damage-lawyer-orlando-2026', permanent: true },
      { source: '/storm-damage-lawyer-pembroke-pines-2026-1', destination: '/storm-damage-lawyer-pembroke-pines-2026', permanent: true },
      { source: '/storm-damage-lawyer-pensacola-2026-1', destination: '/storm-damage-lawyer-pensacola-2026', permanent: true },
      { source: '/storm-damage-lawyer-port-st-lucie-2026-1', destination: '/storm-damage-lawyer-port-st-lucie-2026', permanent: true },
      { source: '/storm-damage-lawyer-port-st-lucie-2026-2', destination: '/storm-damage-lawyer-port-st-lucie-2026', permanent: true },
      { source: '/storm-damage-lawyer-tallahassee-2026-1', destination: '/storm-damage-lawyer-tallahassee-2026', permanent: true },
      { source: '/storm-damage-lawyer-west-palm-beach-2026-1', destination: '/storm-damage-lawyer-west-palm-beach-2026', permanent: true },
      { source: '/storm-damage-lawyer-west-palm-beach-2026-2', destination: '/storm-damage-lawyer-west-palm-beach-2026', permanent: true },
      { source: '/storm-damage-lawyer-west-palm-beach-2026-4', destination: '/storm-damage-lawyer-west-palm-beach-2026', permanent: true },
      { source: '/storm-damage-lawyer-west-palm-beach-2026-5', destination: '/storm-damage-lawyer-west-palm-beach-2026', permanent: true },
      { source: '/tallahassee-hurricane-insurance-lawyer-2026-1', destination: '/tallahassee-hurricane-insurance-lawyer-2026', permanent: true },
      { source: '/tallahassee-storm-claim-lawyer-2026-1', destination: '/tallahassee-storm-claim-lawyer-2026', permanent: true },
      { source: '/tampa-hurricane-insurance-lawyer-2026-1', destination: '/tampa-hurricane-insurance-lawyer-2026', permanent: true },
      { source: '/tampa-mold-damage-attorney-2026-1', destination: '/tampa-mold-damage-attorney-2026', permanent: true },
      { source: '/toxic-mold-insurance-claim-lawyer-hollywood-2026-1', destination: '/toxic-mold-insurance-claim-lawyer-hollywood-2026', permanent: true },
      { source: '/toxic-mold-insurance-claim-lawyer-miami-2026-1', destination: '/toxic-mold-insurance-claim-lawyer-miami-2026', permanent: true },
      { source: '/toxic-mold-insurance-claim-lawyer-orlando-2026-1', destination: '/toxic-mold-insurance-claim-lawyer-orlando-2026', permanent: true },
      { source: '/toxic-mold-insurance-claim-lawyer-west-palm-beach-2026-1', destination: '/toxic-mold-insurance-claim-lawyer-west-palm-beach-2026', permanent: true },
      { source: '/toxic-mold-insurance-coverage-florida-2026-2', destination: '/toxic-mold-insurance-coverage-florida-2026', permanent: true },
      { source: '/toxic-mold-insurance-coverage-florida-2026-41', destination: '/toxic-mold-insurance-coverage-florida-2026', permanent: true },
      { source: '/toxic-mold-lawsuit-fort-lauderdale-2026-2', destination: '/toxic-mold-lawsuit-fort-lauderdale-2026', permanent: true },
      { source: '/toxic-mold-lawsuit-hollywood-2026-1', destination: '/toxic-mold-lawsuit-hollywood-2026', permanent: true },
      { source: '/toxic-mold-lawsuit-miami-2026-1', destination: '/toxic-mold-lawsuit-miami-2026', permanent: true },
      { source: '/toxic-mold-lawsuit-orlando-2026-1', destination: '/toxic-mold-lawsuit-orlando-2026', permanent: true },
      { source: '/toxic-mold-lawsuit-pembroke-pines-2026-4', destination: '/toxic-mold-lawsuit-pembroke-pines-2026', permanent: true },
      { source: '/underpaid-insurance-claim-boca-raton-2026-1', destination: '/underpaid-insurance-claim-boca-raton-2026', permanent: true },
      { source: '/underpaid-insurance-claim-coral-springs-2026-1', destination: '/underpaid-insurance-claim-coral-springs-2026', permanent: true },
      { source: '/underpaid-insurance-claim-jacksonville-2026-3', destination: '/underpaid-insurance-claim-jacksonville-2026', permanent: true },
      { source: '/underpaid-insurance-claim-miami-2026-1', destination: '/underpaid-insurance-claim-miami-2026', permanent: true },
      { source: '/underpaid-insurance-claim-naples-2026-1', destination: '/underpaid-insurance-claim-naples-2026', permanent: true },
      { source: '/underpaid-insurance-claim-tampa-2026-1', destination: '/underpaid-insurance-claim-tampa-2026', permanent: true },
      { source: '/usaa-roof-claim-denied-florida-2026-1', destination: '/usaa-roof-claim-denied-florida-2026', permanent: true },
      { source: '/water-damage-attorney-boca-raton-2026-1', destination: '/water-damage-attorney-boca-raton-2026', permanent: true },
      { source: '/water-damage-attorney-cape-coral-2026-4', destination: '/water-damage-attorney-cape-coral-2026', permanent: true },
      { source: '/water-damage-attorney-hollywood-2026-1', destination: '/water-damage-attorney-hollywood-2026', permanent: true },
      { source: '/water-damage-attorney-miami-2026-1', destination: '/water-damage-attorney-miami-2026', permanent: true },
      { source: '/water-damage-attorney-miami-2026-6', destination: '/water-damage-attorney-miami-2026', permanent: true },
      { source: '/water-damage-attorney-orlando-2026-1', destination: '/water-damage-attorney-orlando-2026', permanent: true },
      { source: '/water-damage-attorney-orlando-2026-2', destination: '/water-damage-attorney-orlando-2026', permanent: true },
      { source: '/water-damage-attorney-sarasota-2026-5', destination: '/water-damage-attorney-sarasota-2026', permanent: true },
      { source: '/water-damage-attorney-st-petersburg-2026-1', destination: '/water-damage-attorney-st-petersburg-2026', permanent: true },
      { source: '/water-damage-attorney-st-petersburg-2026-10', destination: '/water-damage-attorney-st-petersburg-2026', permanent: true },
      { source: '/water-damage-attorney-st-petersburg-2026-4', destination: '/water-damage-attorney-st-petersburg-2026', permanent: true },
      { source: '/water-damage-attorney-tallahassee-2026-1', destination: '/water-damage-attorney-tallahassee-2026', permanent: true },
      { source: '/water-damage-attorney-west-palm-beach-2026-3', destination: '/water-damage-attorney-west-palm-beach-2026', permanent: true },
      { source: '/water-damage-claim-denied-fort-lauderdale-florida-2026-1', destination: '/water-damage-claim-denied-fort-lauderdale-florida-2026', permanent: true },
      { source: '/water-damage-claim-denied-miami-florida-2026-1', destination: '/water-damage-claim-denied-miami-florida-2026', permanent: true },
      { source: '/water-damage-claim-denied-orlando-florida-2026-1', destination: '/water-damage-claim-denied-orlando-florida-2026', permanent: true },
      { source: '/west-palm-beach-hurricane-insurance-lawyer-2026-1', destination: '/west-palm-beach-hurricane-insurance-lawyer-2026', permanent: true },
      { source: '/west-palm-beach-mold-damage-lawyer-2026-1', destination: '/west-palm-beach-mold-damage-lawyer-2026', permanent: true },
      { source: '/west-palm-beach-storm-claim-lawyer-2026-1', destination: '/west-palm-beach-storm-claim-lawyer-2026', permanent: true },
      { source: '/west-palm-beach-storm-claim-lawyer-2026-4', destination: '/west-palm-beach-storm-claim-lawyer-2026', permanent: true },
      { source: '/west-palm-beach-water-damage-insurance-lawyer-2026-3', destination: '/west-palm-beach-water-damage-insurance-lawyer-2026', permanent: true },
      { source: '/west-palm-beach-water-damage-lawyer-2026-1', destination: '/west-palm-beach-water-damage-lawyer-2026', permanent: true },
      { source: '/wind-damage-insurance-attorney-cape-coral-2026-2', destination: '/wind-damage-insurance-attorney-cape-coral-2026', permanent: true },
      { source: '/wind-damage-insurance-attorney-fort-lauderdale-2026-1', destination: '/wind-damage-insurance-attorney-fort-lauderdale-2026', permanent: true },
      { source: '/wind-damage-insurance-attorney-jacksonville-2026-1', destination: '/wind-damage-insurance-attorney-jacksonville-2026', permanent: true },
      { source: '/wind-damage-insurance-attorney-jacksonville-2026-3', destination: '/wind-damage-insurance-attorney-jacksonville-2026', permanent: true },
      { source: '/wind-damage-insurance-attorney-jacksonville-2026-4', destination: '/wind-damage-insurance-attorney-jacksonville-2026', permanent: true },
      { source: '/wind-damage-insurance-attorney-miami-2026-3', destination: '/wind-damage-insurance-attorney-miami-2026', permanent: true },
      { source: '/wind-damage-insurance-attorney-miami-2026-5', destination: '/wind-damage-insurance-attorney-miami-2026', permanent: true },
      { source: '/wind-damage-insurance-attorney-naples-2026-3', destination: '/wind-damage-insurance-attorney-naples-2026', permanent: true },
      { source: '/wind-damage-insurance-attorney-orlando-2026-1', destination: '/wind-damage-insurance-attorney-orlando-2026', permanent: true },
      { source: '/wind-damage-insurance-attorney-orlando-2026-2', destination: '/wind-damage-insurance-attorney-orlando-2026', permanent: true },
      { source: '/wind-damage-insurance-attorney-orlando-2026-3', destination: '/wind-damage-insurance-attorney-orlando-2026', permanent: true },
      { source: '/wind-damage-insurance-attorney-pensacola-2026-1', destination: '/wind-damage-insurance-attorney-pensacola-2026', permanent: true },
      { source: '/wind-damage-insurance-attorney-pensacola-2026-2', destination: '/wind-damage-insurance-attorney-pensacola-2026', permanent: true },
      { source: '/wind-damage-insurance-attorney-sarasota-2026-2', destination: '/wind-damage-insurance-attorney-sarasota-2026', permanent: true },
      { source: '/wind-damage-insurance-attorney-tallahassee-2026-1', destination: '/wind-damage-insurance-attorney-tallahassee-2026', permanent: true },
      { source: '/wind-damage-insurance-attorney-tampa-2026-3', destination: '/wind-damage-insurance-attorney-tampa-2026', permanent: true },
    ];
  },

  async rewrites() {
    return {
      beforeFiles: [
        {
          // Static article page with custom UI — must come before catch-all route
          source: '/case-law-insurance-claim-worth-pursuing-florida-2022-reform',
          destination: '/case-law-insurance-claim-worth-pursuing-florida-2022-reform.html',
        },
        {
          // Static report pages with custom UI
          source: '/reports/florida-insurance-market-january-2026',
          destination: '/reports/florida-insurance-market-january-2026.html',
        },
        {
          source: '/reports/florida-presuit-notice-intelligence-report',
          destination: '/reports/florida-presuit-notice-intelligence-report.html',
        },
        {
          source: '/reports/fee-reform-case-outcomes-dashboard',
          destination: '/reports/fee-reform-case-outcomes-dashboard.html',
        },
      ],
      afterFiles: [
        {
          // Rewrite /sitemaps/1.xml to /api/sitemap/1
          source: '/sitemaps/:page.xml',
          destination: '/api/sitemap/:page',
        },
      ],
      fallback: [],
    };
  },

  async headers() {
    return [
      {
        // Cache all article pages: 24h CDN, serve stale while revalidating
        source: '/:slug*',
        has: [{ type: 'header', key: 'x-nextjs-data', value: undefined }],
        headers: [
          {
            key: 'Cache-Control',
            value: 'public, s-maxage=86400, stale-while-revalidate=3600',
          },
        ],
      },
      {
        // Never cache API routes
        source: '/api/:path*',
        headers: [
          {
            key: 'Cache-Control',
            value: 'no-store',
          },
        ],
      },
    ];
  },
};

export default nextConfig;
