import { NextResponse } from 'next/server';
import piRedirects from './pi-redirects.json';

/**
 * Middleware: PI/SSDI suffix-duplicate 301 redirects (1,958 pages)
 *
 * These are suffix-duplicate pages (e.g. /slug-2026-1 → /slug-2026)
 * generated by the content pipeline. A static JSON map handles all
 * cases including non-trivial redirects (suffix→suffix, base→suffix).
 *
 * FPP redirects (284) remain in next.config.mjs as static redirects.
 */
export function middleware(request) {
  const { pathname } = request.nextUrl;
  const destination = piRedirects[pathname];

  if (destination) {
    const url = request.nextUrl.clone();
    url.pathname = destination;
    return NextResponse.redirect(url, 301);
  }

  return NextResponse.next();
}

export const config = {
  // Only run middleware on paths that could be PI/SSDI suffix duplicates.
  // All PI/SSDI pages contain "2026" or match /car-accident-5.
  // Exclude static assets, API routes, and _next internals.
  matcher: [
    '/((?!api|_next/static|_next/image|favicon\\.ico|robots\\.txt|sitemap|sitemaps|reports).*)',
  ],
};
